networks:
  money_laundering_network:
    driver: bridge
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
    - RABBITMQ_LOG_LEVELS=error
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
    - 15672:15672
    - 5672:5672
    networks:
    - money_laundering_network
  gateway:
    build:
      context: .
      dockerfile: docker/gateway.Dockerfile
    environment:
    - SERVER_HOST=0.0.0.0
    - SERVER_PORT=8080
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    ports:
    - 8080:8080
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - money_laundering_network
  client_0:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    container_name: client_0
    environment:
    - SERVER_HOST=gateway
    - SERVER_PORT=8080
    - INPUT_FILE_TRANSACTIONS=/datasets/client_0_transactions.csv
    - INPUT_FILE_ACCOUNTS=/datasets/client_0_accounts.csv
    - OUTPUT_DIR=/outputs
    volumes:
    - ./datasets:/datasets
    - ./outputs/client_0:/outputs
    depends_on:
    - gateway
    networks:
    - money_laundering_network
  currency_filter_0:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    environment:
    - WORKER_TYPE=CURRENCY_FILTER
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - ID=0
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - money_laundering_network
  max_bank_0:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    environment:
    - WORKER_TYPE=MAX_BANK
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - ID=0
    - INPUT_QUEUE_NAME=max_bank_input
    - OUTPUT_QUEUE_NAME=max_bank_join_input
    - MAX_BATCH_WEIGHT=8000
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - money_laundering_network
  max_bank_join_0:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    environment:
    - WORKER_TYPE=MAX_BANK_JOIN
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - ID=0
    - INPUT_QUEUE_NAME=max_bank_join_input
    - CLIENT_EXCHANGE_NAME=client_results_exchange
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - money_laundering_network
  bank_router_0:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    environment:
    - WORKER_TYPE=BANK_ROUTER
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - ID=0
    - MAX_BANK_WORKER_AMOUNT=1
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - money_laundering_network
  period_filter_0:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    environment:
    - WORKER_TYPE=PERIOD_FILTER
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - ID=0
    - USD_INPUT_QUEUE_NAME=usd_transactions
    - RAW_INPUT_QUEUE_NAME=raw_transactions
    - ORIGIN_DESTINATION_ROUTER_QUEUE_NAME=origin_destination_router
    - PAYMENT_TYPE_FILTER_QUEUE_NAME=payment_type_filter
    - AVG_BY_TYPE_PERIOD_1_QUEUE_NAME=avg_by_type_p1
    - AVG_BY_TYPE_PERIOD_2_QUEUE_NAME=avg_by_type_p2
    - AVG_BY_TYPE_PERIOD_1_START=2024-01-01T00:00:00Z
    - AVG_BY_TYPE_PERIOD_1_END=2024-01-08T23:59:59Z
    - AVG_BY_TYPE_PERIOD_2_START=2024-01-09T00:00:00Z
    - AVG_BY_TYPE_PERIOD_2_END=2024-01-17T23:59:59Z
    - SCATTER_GATHER_PERIOD_START=2024-01-01T00:00:00Z
    - SCATTER_GATHER_PERIOD_END=2024-01-17T23:59:59Z
    - PAYMENT_TYPE_PERIOD_START=2024-01-01T00:00:00Z
    - PAYMENT_TYPE_PERIOD_END=2024-01-17T23:59:59Z
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - money_laundering_network
