networks:
  money_laundering_network:
    driver: bridge
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
    - RABBITMQ_LOG_LEVELS=error
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
    - 15672:15672
    - 5672:5672
    networks:
    - money_laundering_network
  gateway:
    build:
      context: .
      dockerfile: cmd/gateway/Dockerfile
    container_name: gateway
    environment:
    - SERVER_HOST=0.0.0.0
    - SERVER_PORT=8080
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - OUTPUT_QUEUE_NAME=currency_filter_input_queue
    - CLIENT_EXCHANGE_NAME=client_results_exchange
    - RAW_DATA_QUEUE_NAME=raw_transactions
    - LOG_LEVEL=info
    ports:
    - 8080:8080
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - money_laundering_network
  client_0:
    build:
      context: .
      dockerfile: cmd/client/Dockerfile
    container_name: client_0
    environment:
    - ID=0
    - SERVER_HOST=gateway
    - SERVER_PORT=8080
    - INPUT_FILE_TRANSACTIONS=/datasets/client_0_transactions.csv
    - INPUT_FILE_ACCOUNTS=/datasets/client_0_accounts.csv
    - OUTPUT_DIR=/outputs
    - MAX_BATCH_WEIGHT=8000
    - LOG_LEVEL=info
    volumes:
    - ./datasets:/datasets
    - ./outputs/client_0:/outputs
    depends_on:
    - gateway
    networks:
    - money_laundering_network
  client_1:
    build:
      context: .
      dockerfile: cmd/client/Dockerfile
    container_name: client_1
    environment:
    - ID=1
    - SERVER_HOST=gateway
    - SERVER_PORT=8080
    - INPUT_FILE_TRANSACTIONS=/datasets/client_1_transactions.csv
    - INPUT_FILE_ACCOUNTS=/datasets/client_1_accounts.csv
    - OUTPUT_DIR=/outputs
    - MAX_BATCH_WEIGHT=8000
    - LOG_LEVEL=info
    volumes:
    - ./datasets:/datasets
    - ./outputs/client_1:/outputs
    depends_on:
    - gateway
    networks:
    - money_laundering_network
  currency_filter_0:
    build:
      context: .
      dockerfile: cmd/worker/Dockerfile
    container_name: currency_filter_0
    environment:
    - ID=0
    - LOG_LEVEL=info
    - WORKER_TYPE=CURRENCY_FILTER
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - WORKER_COUNT=2
    - WORKER_EXCHANGE_NAME=CURRENCY_FILTER
    - INPUT_QUEUE_NAME=currency_filter_input_queue
    - MICROTRANSACTION_FILTER_QUEUE_NAME=microtransaction_filter_input_queue
    - BANK_ROUTER_QUEUE_NAME=bank_router_input_queue
    - PERIOD_FILTER_QUEUE_NAME=period_filter_input_queue
    - CURRENCY_TO_FILTER=US Dollar
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - money_laundering_network
  currency_filter_1:
    build:
      context: .
      dockerfile: cmd/worker/Dockerfile
    container_name: currency_filter_1
    environment:
    - ID=1
    - LOG_LEVEL=info
    - WORKER_TYPE=CURRENCY_FILTER
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - WORKER_COUNT=2
    - WORKER_EXCHANGE_NAME=CURRENCY_FILTER
    - INPUT_QUEUE_NAME=currency_filter_input_queue
    - MICROTRANSACTION_FILTER_QUEUE_NAME=microtransaction_filter_input_queue
    - BANK_ROUTER_QUEUE_NAME=bank_router_input_queue
    - PERIOD_FILTER_QUEUE_NAME=period_filter_input_queue
    - CURRENCY_TO_FILTER=US Dollar
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - money_laundering_network
  microtransaction_filter_0:
    build:
      context: .
      dockerfile: cmd/worker/Dockerfile
    container_name: microtransaction_filter_0
    environment:
    - ID=0
    - LOG_LEVEL=info
    - WORKER_TYPE=AMOUNT_FILTER
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - WORKER_COUNT=1
    - WORKER_EXCHANGE_NAME=AMOUNT_FILTER
    - INPUT_QUEUE_NAME=microtransaction_filter_input_queue
    - OUTPUT_QUEUE_NAME=microtransaction_join_input_queue
    - AMOUNT_TO_FILTER=50
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - money_laundering_network
  microtransaction_join_0:
    build:
      context: .
      dockerfile: cmd/worker/Dockerfile
    container_name: microtransaction_join_0
    environment:
    - ID=0
    - LOG_LEVEL=info
    - WORKER_TYPE=MICROTRANSACTION_JOIN
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - WORKER_COUNT=1
    - WORKER_EXCHANGE_NAME=MICROTRANSACTION_JOIN
    - INPUT_QUEUE_NAME=microtransaction_join_input_queue
    - CLIENT_EXCHANGE_NAME=client_results_exchange
    - MAX_BATCH_TRANSACTIONS=100
    - MAX_BATCH_BYTES=8000
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - money_laundering_network
  payment_format_filter_0:
    build:
      context: .
      dockerfile: cmd/worker/Dockerfile
    container_name: payment_format_filter_0
    environment:
    - ID=0
    - LOG_LEVEL=info
    - WORKER_TYPE=FORMAT_FILTER
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - WORKER_COUNT=1
    - WORKER_EXCHANGE_NAME=FORMAT_FILTER
    - INPUT_QUEUE_NAME=payment_format_filter_input
    - OUTPUT_QUEUE_NAME=conversion_format_input
    - VALID_PAYMENT_FORMATS=Wire,ACH
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - money_laundering_network
