# Infraestructura Core

global_log_level: debug
gateway:
  env:
    OUTPUT_QUEUE_NAME: currency_filter_input_queue
    CLIENT_EXCHANGE_NAME: client_results_exchange
    MAX_BANK_ROUTER_QUEUE_NAME: bank_router_input_queue
    RAW_DATA_QUEUE_NAME: raw_transactions
  port: 8080
  
rabbitmq:
  amqp_port: 5672
  management_port: 15672

# Nodos de la aplicación
services:
  client:
    count: 1
    datasets_dir: ./datasets
    output_dir: ./outputs  
    max_batch_weight: 8000   
    
  currency_filter:
    count: 2
    worker_type: CURRENCY_FILTER
    env:
      INPUT_QUEUE_NAME: currency_filter_input_queue
      MICROTRANSACTION_FILTER_QUEUE_NAME: microtransaction_filter_input_queue
      BANK_ROUTER_QUEUE_NAME: bank_router_input_queue
      PERIOD_FILTER_QUEUE_NAME: period_filter_input_queue
      CURRENCY_TO_FILTER: "US Dollar"

  microtransaction_filter:
    count: 1
    worker_type: AMOUNT_FILTER
    env:
      INPUT_QUEUE_NAME: microtransaction_filter_input_queue
      OUTPUT_QUEUE_NAME: microtransaction_join_input_queue
      AMOUNT_TO_FILTER: 50

  microtransaction_join:
    count: 1
    worker_type: MICROTRANSACTION_JOIN
    env:
      INPUT_QUEUE_NAME: microtransaction_join_input_queue
      CLIENT_EXCHANGE_NAME: client_results_exchange
      MAX_BATCH_TRANSACTIONS: 100
      MAX_BATCH_BYTES: 8000
    
  bank_router:
    count: 2
    worker_type: BANK_ROUTER
    env:
      INPUT_QUEUE_NAME: bank_router_input_queue
      MAX_BANK_EXCHANGE_NAME: max_bank_input_exchange
      MAX_BANK_WORKER_AMOUNT: 2

  max_bank:
    count: 2
    worker_type: MAX_BANK
    env:
      INPUT_EXCHANGE_NAME: max_bank_input_exchange
      OUTPUT_QUEUE_NAME: max_bank_join_input
      MAX_BATCH_WEIGHT: 8000 

  max_bank_join:
    count: 1
    worker_type: MAX_BANK_JOIN
    env:
      INPUT_QUEUE_NAME: max_bank_join_input
      CLIENT_EXCHANGE_NAME: client_results_exchange
      MAX_BANK_WORKER_AMOUNT: 2
    

  period_filter:
    count: 4
    worker_type: PERIOD_FILTER
    env:
      USD_INPUT_QUEUE_NAME: period_filter_input_queue
      RAW_INPUT_QUEUE_NAME: raw_transactions
      ORIGIN_DESTINATION_ROUTER_QUEUE_NAME: origin_destination_router
      PAYMENT_TYPE_FILTER_QUEUE_NAME: payment_format_filter_input
      AVG_BY_TYPE_PERIOD_1_QUEUE_NAME: avg_by_type_p1
      AVG_BY_TYPE_PERIOD_2_QUEUE_NAME: avg_by_type_p2
      AVG_BY_TYPE_PERIOD_1_START: "2024-01-01T00:00:00Z"
      AVG_BY_TYPE_PERIOD_1_END: "2024-01-08T23:59:59Z"
      AVG_BY_TYPE_PERIOD_2_START: "2024-01-09T00:00:00Z"
      AVG_BY_TYPE_PERIOD_2_END: "2024-01-17T23:59:59Z"
      SCATTER_GATHER_PERIOD_START: "2022-09-01T00:00:00Z"
      SCATTER_GATHER_PERIOD_END: "2022-09-05T23:59:59Z"
      PAYMENT_TYPE_PERIOD_START: "2022-09-01T00:00:00Z"
      PAYMENT_TYPE_PERIOD_END: "2022-09-05T23:59:59Z"
      PAYMENT_TYPE_ROUTER_QUEUE_NAME: payment_type_router_input
      QUERY3_PERIOD_1_START: "2022-09-01T00:00:00Z"
      QUERY3_PERIOD_1_END:   "2022-09-05T23:59:59Z"
      QUERY3_PERIOD_2_START: "2022-09-06T00:00:00Z"
      QUERY3_PERIOD_2_END:   "2022-09-15T23:59:59Z"

  payment_type_router:
    count: 2
    worker_type: PAYMENT_TYPE_ROUTER
    env:
      INPUT_QUEUE_NAME: payment_type_router_input
      PAYMENT_TYPE_EXCHANGE_NAME: payment_type_exchange
      AVG_BY_TYPE_WORKER_AMOUNT: 1

  origin_destination_router:
    count: 2
    worker_type: ORIGIN_DESTINATION_ROUTER

    env:
      INPUT_QUEUE_NAME: origin_destination_router

      GROUP_BY_ORIGIN_EXCHANGE_NAME: group_by_origin
      GROUP_BY_DESTINATION_EXCHANGE_NAME: group_by_destination

      GROUP_BY_ORIGIN_WORKER_AMOUNT: 1
      GROUP_BY_DESTINATION_WORKER_AMOUNT: 1
  
  group_by_origin:
    count: 1
    worker_type: GROUP_BY_ORIGIN

    env:
      INPUT_EXCHANGE_NAME: group_by_origin
      OUTPUT_QUEUE_NAME: grouped_origin_accounts

      MAX_BATCH_WEIGHT: 40000

  group_by_destination:
    count: 1
    worker_type: GROUP_BY_DESTINATION

    env:
      INPUT_EXCHANGE_NAME: group_by_destination
      OUTPUT_QUEUE_NAME: grouped_destination_accounts

      MAX_BATCH_WEIGHT: 40000
  
  origin_intermediary_router:
    count: 1
    worker_type: INTERMEDIARY_ROUTER

    env:
      INPUT_QUEUE_NAME: grouped_origin_accounts

      AGGREGATE_BY_INTERMEDIARY_EXCHANGE_NAME: origin_intermediary_aggregation
      AGGREGATE_BY_INTERMEDIARY_WORKER_AMOUNT: 1

  destination_intermediary_router:
    count: 1
    worker_type: INTERMEDIARY_ROUTER

    env:
      INPUT_QUEUE_NAME: grouped_destination_accounts
      AGGREGATE_BY_INTERMEDIARY_EXCHANGE_NAME: destination_intermediary_aggregation
      AGGREGATE_BY_INTERMEDIARY_WORKER_AMOUNT: 1

  aggregate_by_intermediary:
    count: 1
    worker_type: AGGREGATE_BY_INTERMEDIARY

    env:
      ORIGIN_INPUT_EXCHANGE_NAME: origin_intermediary_aggregation
      DESTINATION_INPUT_EXCHANGE_NAME: destination_intermediary_aggregation

      OUTPUT_QUEUE_NAME: suspicious_paths_output

      MAX_BATCH_WEIGHT: 40000

  avg_by_type:
    count: 0
    worker_type: AVG_BY_TYPE

    env:
      INPUT_EXCHANGE_NAME: payment_type_exchange
      OUTPUT_QUEUE_NAME: avg_by_type_join_input

  avg_by_type_join:
    count: 0
    worker_type: AVG_BY_TYPE_JOIN

    env:
      INPUT_QUEUE_NAME: avg_by_type_join_input
      CLIENT_EXCHANGE_NAME: client_results_exchange
      EXPECTED_EOFS: 1
      
  payment_format_filter:
    count: 2
    worker_type: FORMAT_FILTER
    env:
      INPUT_QUEUE_NAME: payment_format_filter_input
      OUTPUT_QUEUE_NAME: conversion_format_input
      VALID_PAYMENT_FORMATS: "Wire,ACH"

  currency_converter:
    count: 2
    worker_type: CURRENCY_CONVERTER
    env:
      INPUT_QUEUE_NAME: conversion_format_input
      OUTPUT_QUEUE_NAME: filtered_currency_conversion_input
      EXCHANGE_RATE_API_URL: https://api.frankfurter.dev/v2/rates?base=USD

  amount_converted_filter:
    count: 2
    worker_type: AMOUNT_CONVERTED_FILTER
    env:
      INPUT_QUEUE_NAME: filtered_currency_conversion_input
      OUTPUT_QUEUE_NAME: conversion_join_input_queue
      AMOUNT_TO_FILTER: 1.00

  converter_join:
    count: 1
    worker_type: CONVERSION_JOIN
    env:
      INPUT_QUEUE_NAME: conversion_join_input_queue
      CLIENT_EXCHANGE_NAME: client_results_exchange
  
  scatter_gather_join:
    count: 1
    worker_type: SCATTER_GATHER_JOIN

    env:
      INPUT_QUEUE_NAME: suspicious_paths_output
      CLIENT_EXCHANGE_NAME: client_results_exchange
      AGGREGATE_BY_INTERMEDIARY_WORKER_AMOUNT: 1
      MAX_BATCH_WEIGHT: 40000