# Cantidad de instancias para cada tipo de servicio
services:
  client:
    count: 1
    
  currency_filter:
    count: 1
    
  max_bank:
    count: 1
    
  bank_router:
    count: 1

  period_filter:
    count: 1
    usd_input_queue: usd_transactions
    raw_input_queue: raw_transactions

    origin_destination_router_queue: origin_destination_router

    payment_type_queue: payment_type_filter

    avg_by_type_period_1_queue: avg_by_type_p1
    avg_by_type_period_2_queue: avg_by_type_p2

    avg_by_type_period_1_start: "2024-01-01T00:00:00Z"
    avg_by_type_period_1_end: "2024-01-08T23:59:59Z"

    avg_by_type_period_2_start: "2024-01-09T00:00:00Z"
    avg_by_type_period_2_end: "2024-01-17T23:59:59Z"

    scatter_gather_period_start: "2024-01-01T00:00:00Z"
    scatter_gather_period_end: "2024-01-17T23:59:59Z"

    payment_type_period_start: "2024-01-01T00:00:00Z"
    payment_type_period_end: "2024-01-17T23:59:59Z"


# Puertos y configuraciones específicas para cada servicio
gateway:
  port: 8080
  
rabbitmq:
  amqp_port: 5672
  management_port: 15672
