// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/common/inner/protobuf/avgbytypetransaction.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvgByTypePeriod int32

const (
	AvgByTypePeriod_AVGBYTYPE_PERIOD_UNSPECIFIED AvgByTypePeriod = 0
	AvgByTypePeriod_AVGBYTYPE_PERIOD_FIRST       AvgByTypePeriod = 1
	AvgByTypePeriod_AVGBYTYPE_PERIOD_SECOND      AvgByTypePeriod = 2
)

// Enum value maps for AvgByTypePeriod.
var (
	AvgByTypePeriod_name = map[int32]string{
		0: "AVGBYTYPE_PERIOD_UNSPECIFIED",
		1: "AVGBYTYPE_PERIOD_FIRST",
		2: "AVGBYTYPE_PERIOD_SECOND",
	}
	AvgByTypePeriod_value = map[string]int32{
		"AVGBYTYPE_PERIOD_UNSPECIFIED": 0,
		"AVGBYTYPE_PERIOD_FIRST":       1,
		"AVGBYTYPE_PERIOD_SECOND":      2,
	}
)

func (x AvgByTypePeriod) Enum() *AvgByTypePeriod {
	p := new(AvgByTypePeriod)
	*p = x
	return p
}

func (x AvgByTypePeriod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AvgByTypePeriod) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_common_inner_protobuf_avgbytypetransaction_proto_enumTypes[0].Descriptor()
}

func (AvgByTypePeriod) Type() protoreflect.EnumType {
	return &file_internal_common_inner_protobuf_avgbytypetransaction_proto_enumTypes[0]
}

func (x AvgByTypePeriod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AvgByTypePeriod.Descriptor instead.
func (AvgByTypePeriod) EnumDescriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDescGZIP(), []int{0}
}

type AvgByTypeTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	AmountPaid    string                 `protobuf:"bytes,2,opt,name=amount_paid,json=amountPaid,proto3" json:"amount_paid,omitempty"`
	PaymentFormat string                 `protobuf:"bytes,3,opt,name=payment_format,json=paymentFormat,proto3" json:"payment_format,omitempty"`
	Period        AvgByTypePeriod        `protobuf:"varint,4,opt,name=period,proto3,enum=protobuf.AvgByTypePeriod" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvgByTypeTransaction) Reset() {
	*x = AvgByTypeTransaction{}
	mi := &file_internal_common_inner_protobuf_avgbytypetransaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvgByTypeTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvgByTypeTransaction) ProtoMessage() {}

func (x *AvgByTypeTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_avgbytypetransaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvgByTypeTransaction.ProtoReflect.Descriptor instead.
func (*AvgByTypeTransaction) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDescGZIP(), []int{0}
}

func (x *AvgByTypeTransaction) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AvgByTypeTransaction) GetAmountPaid() string {
	if x != nil {
		return x.AmountPaid
	}
	return ""
}

func (x *AvgByTypeTransaction) GetPaymentFormat() string {
	if x != nil {
		return x.PaymentFormat
	}
	return ""
}

func (x *AvgByTypeTransaction) GetPeriod() AvgByTypePeriod {
	if x != nil {
		return x.Period
	}
	return AvgByTypePeriod_AVGBYTYPE_PERIOD_UNSPECIFIED
}

type AvgByTypeTransactionBatch struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Items         []*AvgByTypeTransaction `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvgByTypeTransactionBatch) Reset() {
	*x = AvgByTypeTransactionBatch{}
	mi := &file_internal_common_inner_protobuf_avgbytypetransaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvgByTypeTransactionBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvgByTypeTransactionBatch) ProtoMessage() {}

func (x *AvgByTypeTransactionBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_avgbytypetransaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvgByTypeTransactionBatch.ProtoReflect.Descriptor instead.
func (*AvgByTypeTransactionBatch) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDescGZIP(), []int{1}
}

func (x *AvgByTypeTransactionBatch) GetItems() []*AvgByTypeTransaction {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_internal_common_inner_protobuf_avgbytypetransaction_proto protoreflect.FileDescriptor

const file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDesc = "" +
	"\n" +
	"9internal/common/inner/protobuf/avgbytypetransaction.proto\x12\bprotobuf\"\xab\x01\n" +
	"\x14AvgByTypeTransaction\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1f\n" +
	"\vamount_paid\x18\x02 \x01(\tR\n" +
	"amountPaid\x12%\n" +
	"\x0epayment_format\x18\x03 \x01(\tR\rpaymentFormat\x121\n" +
	"\x06period\x18\x04 \x01(\x0e2\x19.protobuf.AvgByTypePeriodR\x06period\"Q\n" +
	"\x19AvgByTypeTransactionBatch\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.protobuf.AvgByTypeTransactionR\x05items*l\n" +
	"\x0fAvgByTypePeriod\x12 \n" +
	"\x1cAVGBYTYPE_PERIOD_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16AVGBYTYPE_PERIOD_FIRST\x10\x01\x12\x1b\n" +
	"\x17AVGBYTYPE_PERIOD_SECOND\x10\x02B1Z/tp-lavado-dinero/internal/common/inner/protobufb\x06proto3"

var (
	file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDescOnce sync.Once
	file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDescData []byte
)

func file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDescGZIP() []byte {
	file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDescOnce.Do(func() {
		file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDesc), len(file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDesc)))
	})
	return file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDescData
}

var file_internal_common_inner_protobuf_avgbytypetransaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_common_inner_protobuf_avgbytypetransaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_common_inner_protobuf_avgbytypetransaction_proto_goTypes = []any{
	(AvgByTypePeriod)(0),              // 0: protobuf.AvgByTypePeriod
	(*AvgByTypeTransaction)(nil),      // 1: protobuf.AvgByTypeTransaction
	(*AvgByTypeTransactionBatch)(nil), // 2: protobuf.AvgByTypeTransactionBatch
}
var file_internal_common_inner_protobuf_avgbytypetransaction_proto_depIdxs = []int32{
	0, // 0: protobuf.AvgByTypeTransaction.period:type_name -> protobuf.AvgByTypePeriod
	1, // 1: protobuf.AvgByTypeTransactionBatch.items:type_name -> protobuf.AvgByTypeTransaction
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_common_inner_protobuf_avgbytypetransaction_proto_init() }
func file_internal_common_inner_protobuf_avgbytypetransaction_proto_init() {
	if File_internal_common_inner_protobuf_avgbytypetransaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDesc), len(file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_common_inner_protobuf_avgbytypetransaction_proto_goTypes,
		DependencyIndexes: file_internal_common_inner_protobuf_avgbytypetransaction_proto_depIdxs,
		EnumInfos:         file_internal_common_inner_protobuf_avgbytypetransaction_proto_enumTypes,
		MessageInfos:      file_internal_common_inner_protobuf_avgbytypetransaction_proto_msgTypes,
	}.Build()
	File_internal_common_inner_protobuf_avgbytypetransaction_proto = out.File
	file_internal_common_inner_protobuf_avgbytypetransaction_proto_goTypes = nil
	file_internal_common_inner_protobuf_avgbytypetransaction_proto_depIdxs = nil
}
