// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/common/inner/protobuf/protomessages/conversion.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ToConvertTransaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AmountPaid      string                 `protobuf:"bytes,2,opt,name=amount_paid,json=amountPaid,proto3" json:"amount_paid,omitempty"`
	PaymentCurrency string                 `protobuf:"bytes,3,opt,name=payment_currency,json=paymentCurrency,proto3" json:"payment_currency,omitempty"`
	PaymentFormat   string                 `protobuf:"bytes,4,opt,name=payment_format,json=paymentFormat,proto3" json:"payment_format,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToConvertTransaction) Reset() {
	*x = ToConvertTransaction{}
	mi := &file_internal_common_inner_protobuf_protomessages_conversion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToConvertTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToConvertTransaction) ProtoMessage() {}

func (x *ToConvertTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_protomessages_conversion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToConvertTransaction.ProtoReflect.Descriptor instead.
func (*ToConvertTransaction) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_protomessages_conversion_proto_rawDescGZIP(), []int{0}
}

func (x *ToConvertTransaction) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ToConvertTransaction) GetAmountPaid() string {
	if x != nil {
		return x.AmountPaid
	}
	return ""
}

func (x *ToConvertTransaction) GetPaymentCurrency() string {
	if x != nil {
		return x.PaymentCurrency
	}
	return ""
}

func (x *ToConvertTransaction) GetPaymentFormat() string {
	if x != nil {
		return x.PaymentFormat
	}
	return ""
}

type ToConvertTransactionBatch struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Items         []*ToConvertTransaction `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToConvertTransactionBatch) Reset() {
	*x = ToConvertTransactionBatch{}
	mi := &file_internal_common_inner_protobuf_protomessages_conversion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToConvertTransactionBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToConvertTransactionBatch) ProtoMessage() {}

func (x *ToConvertTransactionBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_protomessages_conversion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToConvertTransactionBatch.ProtoReflect.Descriptor instead.
func (*ToConvertTransactionBatch) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_protomessages_conversion_proto_rawDescGZIP(), []int{1}
}

func (x *ToConvertTransactionBatch) GetItems() []*ToConvertTransaction {
	if x != nil {
		return x.Items
	}
	return nil
}

type ToConvertPeriodFiltered struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AmountPaid      string                 `protobuf:"bytes,1,opt,name=amount_paid,json=amountPaid,proto3" json:"amount_paid,omitempty"`
	PaymentCurrency string                 `protobuf:"bytes,2,opt,name=payment_currency,json=paymentCurrency,proto3" json:"payment_currency,omitempty"`
	PaymentFormat   string                 `protobuf:"bytes,3,opt,name=payment_format,json=paymentFormat,proto3" json:"payment_format,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToConvertPeriodFiltered) Reset() {
	*x = ToConvertPeriodFiltered{}
	mi := &file_internal_common_inner_protobuf_protomessages_conversion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToConvertPeriodFiltered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToConvertPeriodFiltered) ProtoMessage() {}

func (x *ToConvertPeriodFiltered) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_protomessages_conversion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToConvertPeriodFiltered.ProtoReflect.Descriptor instead.
func (*ToConvertPeriodFiltered) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_protomessages_conversion_proto_rawDescGZIP(), []int{2}
}

func (x *ToConvertPeriodFiltered) GetAmountPaid() string {
	if x != nil {
		return x.AmountPaid
	}
	return ""
}

func (x *ToConvertPeriodFiltered) GetPaymentCurrency() string {
	if x != nil {
		return x.PaymentCurrency
	}
	return ""
}

func (x *ToConvertPeriodFiltered) GetPaymentFormat() string {
	if x != nil {
		return x.PaymentFormat
	}
	return ""
}

func (x *ToConvertPeriodFiltered) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ToConvertPeriodFilteredBatch struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Items         []*ToConvertPeriodFiltered `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToConvertPeriodFilteredBatch) Reset() {
	*x = ToConvertPeriodFilteredBatch{}
	mi := &file_internal_common_inner_protobuf_protomessages_conversion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToConvertPeriodFilteredBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToConvertPeriodFilteredBatch) ProtoMessage() {}

func (x *ToConvertPeriodFilteredBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_protomessages_conversion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToConvertPeriodFilteredBatch.ProtoReflect.Descriptor instead.
func (*ToConvertPeriodFilteredBatch) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_protomessages_conversion_proto_rawDescGZIP(), []int{3}
}

func (x *ToConvertPeriodFilteredBatch) GetItems() []*ToConvertPeriodFiltered {
	if x != nil {
		return x.Items
	}
	return nil
}

type ToConvertTypeFilteredPayment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AmountPaid      string                 `protobuf:"bytes,1,opt,name=amount_paid,json=amountPaid,proto3" json:"amount_paid,omitempty"`
	PaymentCurrency string                 `protobuf:"bytes,2,opt,name=payment_currency,json=paymentCurrency,proto3" json:"payment_currency,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToConvertTypeFilteredPayment) Reset() {
	*x = ToConvertTypeFilteredPayment{}
	mi := &file_internal_common_inner_protobuf_protomessages_conversion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToConvertTypeFilteredPayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToConvertTypeFilteredPayment) ProtoMessage() {}

func (x *ToConvertTypeFilteredPayment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_protomessages_conversion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToConvertTypeFilteredPayment.ProtoReflect.Descriptor instead.
func (*ToConvertTypeFilteredPayment) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_protomessages_conversion_proto_rawDescGZIP(), []int{4}
}

func (x *ToConvertTypeFilteredPayment) GetAmountPaid() string {
	if x != nil {
		return x.AmountPaid
	}
	return ""
}

func (x *ToConvertTypeFilteredPayment) GetPaymentCurrency() string {
	if x != nil {
		return x.PaymentCurrency
	}
	return ""
}

func (x *ToConvertTypeFilteredPayment) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ToConvertTypeFilteredPaymentBatch struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Items         []*ToConvertTypeFilteredPayment `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToConvertTypeFilteredPaymentBatch) Reset() {
	*x = ToConvertTypeFilteredPaymentBatch{}
	mi := &file_internal_common_inner_protobuf_protomessages_conversion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToConvertTypeFilteredPaymentBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToConvertTypeFilteredPaymentBatch) ProtoMessage() {}

func (x *ToConvertTypeFilteredPaymentBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_protomessages_conversion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToConvertTypeFilteredPaymentBatch.ProtoReflect.Descriptor instead.
func (*ToConvertTypeFilteredPaymentBatch) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_protomessages_conversion_proto_rawDescGZIP(), []int{5}
}

func (x *ToConvertTypeFilteredPaymentBatch) GetItems() []*ToConvertTypeFilteredPayment {
	if x != nil {
		return x.Items
	}
	return nil
}

type ConvertedAmount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertedAmount) Reset() {
	*x = ConvertedAmount{}
	mi := &file_internal_common_inner_protobuf_protomessages_conversion_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertedAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertedAmount) ProtoMessage() {}

func (x *ConvertedAmount) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_protomessages_conversion_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertedAmount.ProtoReflect.Descriptor instead.
func (*ConvertedAmount) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_protomessages_conversion_proto_rawDescGZIP(), []int{6}
}

func (x *ConvertedAmount) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ConvertedAmountBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ConvertedAmount     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertedAmountBatch) Reset() {
	*x = ConvertedAmountBatch{}
	mi := &file_internal_common_inner_protobuf_protomessages_conversion_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertedAmountBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertedAmountBatch) ProtoMessage() {}

func (x *ConvertedAmountBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_protomessages_conversion_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertedAmountBatch.ProtoReflect.Descriptor instead.
func (*ConvertedAmountBatch) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_protomessages_conversion_proto_rawDescGZIP(), []int{7}
}

func (x *ConvertedAmountBatch) GetItems() []*ConvertedAmount {
	if x != nil {
		return x.Items
	}
	return nil
}

type ConvertedMicroPaymentResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertedMicroPaymentResult) Reset() {
	*x = ConvertedMicroPaymentResult{}
	mi := &file_internal_common_inner_protobuf_protomessages_conversion_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertedMicroPaymentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertedMicroPaymentResult) ProtoMessage() {}

func (x *ConvertedMicroPaymentResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_protomessages_conversion_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertedMicroPaymentResult.ProtoReflect.Descriptor instead.
func (*ConvertedMicroPaymentResult) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_protomessages_conversion_proto_rawDescGZIP(), []int{8}
}

func (x *ConvertedMicroPaymentResult) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ConvertedMicroPaymentResultBatch struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Results       []*ConvertedMicroPaymentResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertedMicroPaymentResultBatch) Reset() {
	*x = ConvertedMicroPaymentResultBatch{}
	mi := &file_internal_common_inner_protobuf_protomessages_conversion_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertedMicroPaymentResultBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertedMicroPaymentResultBatch) ProtoMessage() {}

func (x *ConvertedMicroPaymentResultBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_protomessages_conversion_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertedMicroPaymentResultBatch.ProtoReflect.Descriptor instead.
func (*ConvertedMicroPaymentResultBatch) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_protomessages_conversion_proto_rawDescGZIP(), []int{9}
}

func (x *ConvertedMicroPaymentResultBatch) GetResults() []*ConvertedMicroPaymentResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_internal_common_inner_protobuf_protomessages_conversion_proto protoreflect.FileDescriptor

const file_internal_common_inner_protobuf_protomessages_conversion_proto_rawDesc = "" +
	"\n" +
	"=internal/common/inner/protobuf/protomessages/conversion.proto\x12\bprotobuf\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc3\x01\n" +
	"\x14ToConvertTransaction\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\vamount_paid\x18\x02 \x01(\tR\n" +
	"amountPaid\x12)\n" +
	"\x10payment_currency\x18\x03 \x01(\tR\x0fpaymentCurrency\x12%\n" +
	"\x0epayment_format\x18\x04 \x01(\tR\rpaymentFormat\"Q\n" +
	"\x19ToConvertTransactionBatch\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.protobuf.ToConvertTransactionR\x05items\"\xc6\x01\n" +
	"\x17ToConvertPeriodFiltered\x12\x1f\n" +
	"\vamount_paid\x18\x01 \x01(\tR\n" +
	"amountPaid\x12)\n" +
	"\x10payment_currency\x18\x02 \x01(\tR\x0fpaymentCurrency\x12%\n" +
	"\x0epayment_format\x18\x03 \x01(\tR\rpaymentFormat\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"W\n" +
	"\x1cToConvertPeriodFilteredBatch\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.protobuf.ToConvertPeriodFilteredR\x05items\"\xa4\x01\n" +
	"\x1cToConvertTypeFilteredPayment\x12\x1f\n" +
	"\vamount_paid\x18\x01 \x01(\tR\n" +
	"amountPaid\x12)\n" +
	"\x10payment_currency\x18\x02 \x01(\tR\x0fpaymentCurrency\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"a\n" +
	"!ToConvertTypeFilteredPaymentBatch\x12<\n" +
	"\x05items\x18\x01 \x03(\v2&.protobuf.ToConvertTypeFilteredPaymentR\x05items\")\n" +
	"\x0fConvertedAmount\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\"G\n" +
	"\x14ConvertedAmountBatch\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.protobuf.ConvertedAmountR\x05items\"3\n" +
	"\x1bConvertedMicroPaymentResult\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"c\n" +
	" ConvertedMicroPaymentResultBatch\x12?\n" +
	"\aresults\x18\x01 \x03(\v2%.protobuf.ConvertedMicroPaymentResultR\aresultsB1Z/tp-lavado-dinero/internal/common/inner/protobufb\x06proto3"

var (
	file_internal_common_inner_protobuf_protomessages_conversion_proto_rawDescOnce sync.Once
	file_internal_common_inner_protobuf_protomessages_conversion_proto_rawDescData []byte
)

func file_internal_common_inner_protobuf_protomessages_conversion_proto_rawDescGZIP() []byte {
	file_internal_common_inner_protobuf_protomessages_conversion_proto_rawDescOnce.Do(func() {
		file_internal_common_inner_protobuf_protomessages_conversion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_protomessages_conversion_proto_rawDesc), len(file_internal_common_inner_protobuf_protomessages_conversion_proto_rawDesc)))
	})
	return file_internal_common_inner_protobuf_protomessages_conversion_proto_rawDescData
}

var file_internal_common_inner_protobuf_protomessages_conversion_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_common_inner_protobuf_protomessages_conversion_proto_goTypes = []any{
	(*ToConvertTransaction)(nil),              // 0: protobuf.ToConvertTransaction
	(*ToConvertTransactionBatch)(nil),         // 1: protobuf.ToConvertTransactionBatch
	(*ToConvertPeriodFiltered)(nil),           // 2: protobuf.ToConvertPeriodFiltered
	(*ToConvertPeriodFilteredBatch)(nil),      // 3: protobuf.ToConvertPeriodFilteredBatch
	(*ToConvertTypeFilteredPayment)(nil),      // 4: protobuf.ToConvertTypeFilteredPayment
	(*ToConvertTypeFilteredPaymentBatch)(nil), // 5: protobuf.ToConvertTypeFilteredPaymentBatch
	(*ConvertedAmount)(nil),                   // 6: protobuf.ConvertedAmount
	(*ConvertedAmountBatch)(nil),              // 7: protobuf.ConvertedAmountBatch
	(*ConvertedMicroPaymentResult)(nil),       // 8: protobuf.ConvertedMicroPaymentResult
	(*ConvertedMicroPaymentResultBatch)(nil),  // 9: protobuf.ConvertedMicroPaymentResultBatch
	(*timestamppb.Timestamp)(nil),             // 10: google.protobuf.Timestamp
}
var file_internal_common_inner_protobuf_protomessages_conversion_proto_depIdxs = []int32{
	10, // 0: protobuf.ToConvertTransaction.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: protobuf.ToConvertTransactionBatch.items:type_name -> protobuf.ToConvertTransaction
	10, // 2: protobuf.ToConvertPeriodFiltered.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 3: protobuf.ToConvertPeriodFilteredBatch.items:type_name -> protobuf.ToConvertPeriodFiltered
	10, // 4: protobuf.ToConvertTypeFilteredPayment.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 5: protobuf.ToConvertTypeFilteredPaymentBatch.items:type_name -> protobuf.ToConvertTypeFilteredPayment
	6,  // 6: protobuf.ConvertedAmountBatch.items:type_name -> protobuf.ConvertedAmount
	8,  // 7: protobuf.ConvertedMicroPaymentResultBatch.results:type_name -> protobuf.ConvertedMicroPaymentResult
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_internal_common_inner_protobuf_protomessages_conversion_proto_init() }
func file_internal_common_inner_protobuf_protomessages_conversion_proto_init() {
	if File_internal_common_inner_protobuf_protomessages_conversion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_protomessages_conversion_proto_rawDesc), len(file_internal_common_inner_protobuf_protomessages_conversion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_common_inner_protobuf_protomessages_conversion_proto_goTypes,
		DependencyIndexes: file_internal_common_inner_protobuf_protomessages_conversion_proto_depIdxs,
		MessageInfos:      file_internal_common_inner_protobuf_protomessages_conversion_proto_msgTypes,
	}.Build()
	File_internal_common_inner_protobuf_protomessages_conversion_proto = out.File
	file_internal_common_inner_protobuf_protomessages_conversion_proto_goTypes = nil
	file_internal_common_inner_protobuf_protomessages_conversion_proto_depIdxs = nil
}
