// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/common/inner/protobuf/protomessages/coordination.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CoordinationMessageType int32

const (
	CoordinationMessageType_eof_arrived       CoordinationMessageType = 0
	CoordinationMessageType_batch_information CoordinationMessageType = 1
	CoordinationMessageType_wakeup            CoordinationMessageType = 2
)

// Enum value maps for CoordinationMessageType.
var (
	CoordinationMessageType_name = map[int32]string{
		0: "eof_arrived",
		1: "batch_information",
		2: "wakeup",
	}
	CoordinationMessageType_value = map[string]int32{
		"eof_arrived":       0,
		"batch_information": 1,
		"wakeup":            2,
	}
)

func (x CoordinationMessageType) Enum() *CoordinationMessageType {
	p := new(CoordinationMessageType)
	*p = x
	return p
}

func (x CoordinationMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoordinationMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_common_inner_protobuf_protomessages_coordination_proto_enumTypes[0].Descriptor()
}

func (CoordinationMessageType) Type() protoreflect.EnumType {
	return &file_internal_common_inner_protobuf_protomessages_coordination_proto_enumTypes[0]
}

func (x CoordinationMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoordinationMessageType.Descriptor instead.
func (CoordinationMessageType) EnumDescriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDescGZIP(), []int{0}
}

type EOFCoordination struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Type          CoordinationMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=protobuf.CoordinationMessageType" json:"type,omitempty"`
	ClientId      string                  `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	SenderId      uint32                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ExpectedTotal uint64                  `protobuf:"varint,4,opt,name=expected_total,json=expectedTotal,proto3" json:"expected_total,omitempty"`
	EofSeen       uint32                  `protobuf:"varint,5,opt,name=eof_seen,json=eofSeen,proto3" json:"eof_seen,omitempty"`
	EofID         string                  `protobuf:"bytes,6,opt,name=eofID,proto3" json:"eofID,omitempty"`
	Information   []*BatchInformation     `protobuf:"bytes,7,rep,name=information,proto3" json:"information,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EOFCoordination) Reset() {
	*x = EOFCoordination{}
	mi := &file_internal_common_inner_protobuf_protomessages_coordination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EOFCoordination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EOFCoordination) ProtoMessage() {}

func (x *EOFCoordination) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_protomessages_coordination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EOFCoordination.ProtoReflect.Descriptor instead.
func (*EOFCoordination) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDescGZIP(), []int{0}
}

func (x *EOFCoordination) GetType() CoordinationMessageType {
	if x != nil {
		return x.Type
	}
	return CoordinationMessageType_eof_arrived
}

func (x *EOFCoordination) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *EOFCoordination) GetSenderId() uint32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *EOFCoordination) GetExpectedTotal() uint64 {
	if x != nil {
		return x.ExpectedTotal
	}
	return 0
}

func (x *EOFCoordination) GetEofSeen() uint32 {
	if x != nil {
		return x.EofSeen
	}
	return 0
}

func (x *EOFCoordination) GetEofID() string {
	if x != nil {
		return x.EofID
	}
	return ""
}

func (x *EOFCoordination) GetInformation() []*BatchInformation {
	if x != nil {
		return x.Information
	}
	return nil
}

type BatchInformation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BatchID        string                 `protobuf:"bytes,1,opt,name=batchID,proto3" json:"batchID,omitempty"`
	ProcessedCount uint64                 `protobuf:"varint,2,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"`
	SurvivorCount  uint64                 `protobuf:"varint,3,opt,name=survivor_count,json=survivorCount,proto3" json:"survivor_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchInformation) Reset() {
	*x = BatchInformation{}
	mi := &file_internal_common_inner_protobuf_protomessages_coordination_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInformation) ProtoMessage() {}

func (x *BatchInformation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_protomessages_coordination_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInformation.ProtoReflect.Descriptor instead.
func (*BatchInformation) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDescGZIP(), []int{1}
}

func (x *BatchInformation) GetBatchID() string {
	if x != nil {
		return x.BatchID
	}
	return ""
}

func (x *BatchInformation) GetProcessedCount() uint64 {
	if x != nil {
		return x.ProcessedCount
	}
	return 0
}

func (x *BatchInformation) GetSurvivorCount() uint64 {
	if x != nil {
		return x.SurvivorCount
	}
	return 0
}

var File_internal_common_inner_protobuf_protomessages_coordination_proto protoreflect.FileDescriptor

const file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDesc = "" +
	"\n" +
	"?internal/common/inner/protobuf/protomessages/coordination.proto\x12\bprotobuf\"\x98\x02\n" +
	"\x0fEOFCoordination\x125\n" +
	"\x04type\x18\x01 \x01(\x0e2!.protobuf.CoordinationMessageTypeR\x04type\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\rR\bsenderId\x12%\n" +
	"\x0eexpected_total\x18\x04 \x01(\x04R\rexpectedTotal\x12\x19\n" +
	"\beof_seen\x18\x05 \x01(\rR\aeofSeen\x12\x14\n" +
	"\x05eofID\x18\x06 \x01(\tR\x05eofID\x12<\n" +
	"\vinformation\x18\a \x03(\v2\x1a.protobuf.BatchInformationR\vinformation\"|\n" +
	"\x10BatchInformation\x12\x18\n" +
	"\abatchID\x18\x01 \x01(\tR\abatchID\x12'\n" +
	"\x0fprocessed_count\x18\x02 \x01(\x04R\x0eprocessedCount\x12%\n" +
	"\x0esurvivor_count\x18\x03 \x01(\x04R\rsurvivorCount*M\n" +
	"\x17CoordinationMessageType\x12\x0f\n" +
	"\veof_arrived\x10\x00\x12\x15\n" +
	"\x11batch_information\x10\x01\x12\n" +
	"\n" +
	"\x06wakeup\x10\x02B1Z/tp-lavado-dinero/internal/common/inner/protobufb\x06proto3"

var (
	file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDescOnce sync.Once
	file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDescData []byte
)

func file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDescGZIP() []byte {
	file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDescOnce.Do(func() {
		file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDesc), len(file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDesc)))
	})
	return file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDescData
}

var file_internal_common_inner_protobuf_protomessages_coordination_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_common_inner_protobuf_protomessages_coordination_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_common_inner_protobuf_protomessages_coordination_proto_goTypes = []any{
	(CoordinationMessageType)(0), // 0: protobuf.CoordinationMessageType
	(*EOFCoordination)(nil),      // 1: protobuf.EOFCoordination
	(*BatchInformation)(nil),     // 2: protobuf.BatchInformation
}
var file_internal_common_inner_protobuf_protomessages_coordination_proto_depIdxs = []int32{
	0, // 0: protobuf.EOFCoordination.type:type_name -> protobuf.CoordinationMessageType
	2, // 1: protobuf.EOFCoordination.information:type_name -> protobuf.BatchInformation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_common_inner_protobuf_protomessages_coordination_proto_init() }
func file_internal_common_inner_protobuf_protomessages_coordination_proto_init() {
	if File_internal_common_inner_protobuf_protomessages_coordination_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDesc), len(file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_common_inner_protobuf_protomessages_coordination_proto_goTypes,
		DependencyIndexes: file_internal_common_inner_protobuf_protomessages_coordination_proto_depIdxs,
		EnumInfos:         file_internal_common_inner_protobuf_protomessages_coordination_proto_enumTypes,
		MessageInfos:      file_internal_common_inner_protobuf_protomessages_coordination_proto_msgTypes,
	}.Build()
	File_internal_common_inner_protobuf_protomessages_coordination_proto = out.File
	file_internal_common_inner_protobuf_protomessages_coordination_proto_goTypes = nil
	file_internal_common_inner_protobuf_protomessages_coordination_proto_depIdxs = nil
}
