// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/common/inner/protobuf/protomessages/coordinatorok.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CoordinatorOK struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int32                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorOK) Reset() {
	*x = CoordinatorOK{}
	mi := &file_internal_common_inner_protobuf_protomessages_coordinatorok_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorOK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorOK) ProtoMessage() {}

func (x *CoordinatorOK) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_protomessages_coordinatorok_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorOK.ProtoReflect.Descriptor instead.
func (*CoordinatorOK) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_protomessages_coordinatorok_proto_rawDescGZIP(), []int{0}
}

func (x *CoordinatorOK) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

var File_internal_common_inner_protobuf_protomessages_coordinatorok_proto protoreflect.FileDescriptor

const file_internal_common_inner_protobuf_protomessages_coordinatorok_proto_rawDesc = "" +
	"\n" +
	"@internal/common/inner/protobuf/protomessages/coordinatorok.proto\x12\bprotobuf\",\n" +
	"\rCoordinatorOK\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x05R\bsenderIdB1Z/tp-lavado-dinero/internal/common/inner/protobufb\x06proto3"

var (
	file_internal_common_inner_protobuf_protomessages_coordinatorok_proto_rawDescOnce sync.Once
	file_internal_common_inner_protobuf_protomessages_coordinatorok_proto_rawDescData []byte
)

func file_internal_common_inner_protobuf_protomessages_coordinatorok_proto_rawDescGZIP() []byte {
	file_internal_common_inner_protobuf_protomessages_coordinatorok_proto_rawDescOnce.Do(func() {
		file_internal_common_inner_protobuf_protomessages_coordinatorok_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_protomessages_coordinatorok_proto_rawDesc), len(file_internal_common_inner_protobuf_protomessages_coordinatorok_proto_rawDesc)))
	})
	return file_internal_common_inner_protobuf_protomessages_coordinatorok_proto_rawDescData
}

var file_internal_common_inner_protobuf_protomessages_coordinatorok_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_common_inner_protobuf_protomessages_coordinatorok_proto_goTypes = []any{
	(*CoordinatorOK)(nil), // 0: protobuf.CoordinatorOK
}
var file_internal_common_inner_protobuf_protomessages_coordinatorok_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_common_inner_protobuf_protomessages_coordinatorok_proto_init() }
func file_internal_common_inner_protobuf_protomessages_coordinatorok_proto_init() {
	if File_internal_common_inner_protobuf_protomessages_coordinatorok_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_protomessages_coordinatorok_proto_rawDesc), len(file_internal_common_inner_protobuf_protomessages_coordinatorok_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_common_inner_protobuf_protomessages_coordinatorok_proto_goTypes,
		DependencyIndexes: file_internal_common_inner_protobuf_protomessages_coordinatorok_proto_depIdxs,
		MessageInfos:      file_internal_common_inner_protobuf_protomessages_coordinatorok_proto_msgTypes,
	}.Build()
	File_internal_common_inner_protobuf_protomessages_coordinatorok_proto = out.File
	file_internal_common_inner_protobuf_protomessages_coordinatorok_proto_goTypes = nil
	file_internal_common_inner_protobuf_protomessages_coordinatorok_proto_depIdxs = nil
}
