// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/common/inner/protobuf/protomessages/coordination.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EOFCoordination struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientId       string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	SenderId       uint32                 `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ProcessedCount uint64                 `protobuf:"varint,3,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"`
	SurvivorCount  uint64                 `protobuf:"varint,4,opt,name=survivor_count,json=survivorCount,proto3" json:"survivor_count,omitempty"`
	ExpectedTotal  uint64                 `protobuf:"varint,6,opt,name=expected_total,json=expectedTotal,proto3" json:"expected_total,omitempty"`
	EofArrived     bool                   `protobuf:"varint,7,opt,name=eof_arrived,json=eofArrived,proto3" json:"eof_arrived,omitempty"`
	EofSeen        uint32                 `protobuf:"varint,8,opt,name=eof_seen,json=eofSeen,proto3" json:"eof_seen,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EOFCoordination) Reset() {
	*x = EOFCoordination{}
	mi := &file_internal_common_inner_protobuf_protomessages_coordination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EOFCoordination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EOFCoordination) ProtoMessage() {}

func (x *EOFCoordination) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_protomessages_coordination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EOFCoordination.ProtoReflect.Descriptor instead.
func (*EOFCoordination) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDescGZIP(), []int{0}
}

func (x *EOFCoordination) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *EOFCoordination) GetSenderId() uint32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *EOFCoordination) GetProcessedCount() uint64 {
	if x != nil {
		return x.ProcessedCount
	}
	return 0
}

func (x *EOFCoordination) GetSurvivorCount() uint64 {
	if x != nil {
		return x.SurvivorCount
	}
	return 0
}

func (x *EOFCoordination) GetExpectedTotal() uint64 {
	if x != nil {
		return x.ExpectedTotal
	}
	return 0
}

func (x *EOFCoordination) GetEofArrived() bool {
	if x != nil {
		return x.EofArrived
	}
	return false
}

func (x *EOFCoordination) GetEofSeen() uint32 {
	if x != nil {
		return x.EofSeen
	}
	return 0
}

var File_internal_common_inner_protobuf_protomessages_coordination_proto protoreflect.FileDescriptor

const file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDesc = "" +
	"\n" +
	"?internal/common/inner/protobuf/protomessages/coordination.proto\x12\bprotobuf\"\xfe\x01\n" +
	"\x0fEOFCoordination\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\rR\bsenderId\x12'\n" +
	"\x0fprocessed_count\x18\x03 \x01(\x04R\x0eprocessedCount\x12%\n" +
	"\x0esurvivor_count\x18\x04 \x01(\x04R\rsurvivorCount\x12%\n" +
	"\x0eexpected_total\x18\x06 \x01(\x04R\rexpectedTotal\x12\x1f\n" +
	"\veof_arrived\x18\a \x01(\bR\n" +
	"eofArrived\x12\x19\n" +
	"\beof_seen\x18\b \x01(\rR\aeofSeenB1Z/tp-lavado-dinero/internal/common/inner/protobufb\x06proto3"

var (
	file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDescOnce sync.Once
	file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDescData []byte
)

func file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDescGZIP() []byte {
	file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDescOnce.Do(func() {
		file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDesc), len(file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDesc)))
	})
	return file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDescData
}

var file_internal_common_inner_protobuf_protomessages_coordination_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_common_inner_protobuf_protomessages_coordination_proto_goTypes = []any{
	(*EOFCoordination)(nil), // 0: protobuf.EOFCoordination
}
var file_internal_common_inner_protobuf_protomessages_coordination_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_common_inner_protobuf_protomessages_coordination_proto_init() }
func file_internal_common_inner_protobuf_protomessages_coordination_proto_init() {
	if File_internal_common_inner_protobuf_protomessages_coordination_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDesc), len(file_internal_common_inner_protobuf_protomessages_coordination_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_common_inner_protobuf_protomessages_coordination_proto_goTypes,
		DependencyIndexes: file_internal_common_inner_protobuf_protomessages_coordination_proto_depIdxs,
		MessageInfos:      file_internal_common_inner_protobuf_protomessages_coordination_proto_msgTypes,
	}.Build()
	File_internal_common_inner_protobuf_protomessages_coordination_proto = out.File
	file_internal_common_inner_protobuf_protomessages_coordination_proto_goTypes = nil
	file_internal_common_inner_protobuf_protomessages_coordination_proto_depIdxs = nil
}
