// heartbeat.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/common/inner/protobuf/protomessages/heartbeat.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerName string                 `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_common_inner_protobuf_protomessages_heartbeat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_protomessages_heartbeat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_protomessages_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *Heartbeat) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_internal_common_inner_protobuf_protomessages_heartbeat_proto protoreflect.FileDescriptor

const file_internal_common_inner_protobuf_protomessages_heartbeat_proto_rawDesc = "" +
	"\n" +
	"<internal/common/inner/protobuf/protomessages/heartbeat.proto\x12\bprotobuf\"P\n" +
	"\tHeartbeat\x12%\n" +
	"\x0econtainer_name\x18\x01 \x01(\tR\rcontainerName\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestampB1Z/tp-lavado-dinero/internal/common/inner/protobufb\x06proto3"

var (
	file_internal_common_inner_protobuf_protomessages_heartbeat_proto_rawDescOnce sync.Once
	file_internal_common_inner_protobuf_protomessages_heartbeat_proto_rawDescData []byte
)

func file_internal_common_inner_protobuf_protomessages_heartbeat_proto_rawDescGZIP() []byte {
	file_internal_common_inner_protobuf_protomessages_heartbeat_proto_rawDescOnce.Do(func() {
		file_internal_common_inner_protobuf_protomessages_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_protomessages_heartbeat_proto_rawDesc), len(file_internal_common_inner_protobuf_protomessages_heartbeat_proto_rawDesc)))
	})
	return file_internal_common_inner_protobuf_protomessages_heartbeat_proto_rawDescData
}

var file_internal_common_inner_protobuf_protomessages_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_common_inner_protobuf_protomessages_heartbeat_proto_goTypes = []any{
	(*Heartbeat)(nil), // 0: protobuf.Heartbeat
}
var file_internal_common_inner_protobuf_protomessages_heartbeat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_common_inner_protobuf_protomessages_heartbeat_proto_init() }
func file_internal_common_inner_protobuf_protomessages_heartbeat_proto_init() {
	if File_internal_common_inner_protobuf_protomessages_heartbeat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_protomessages_heartbeat_proto_rawDesc), len(file_internal_common_inner_protobuf_protomessages_heartbeat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_common_inner_protobuf_protomessages_heartbeat_proto_goTypes,
		DependencyIndexes: file_internal_common_inner_protobuf_protomessages_heartbeat_proto_depIdxs,
		MessageInfos:      file_internal_common_inner_protobuf_protomessages_heartbeat_proto_msgTypes,
	}.Build()
	File_internal_common_inner_protobuf_protomessages_heartbeat_proto = out.File
	file_internal_common_inner_protobuf_protomessages_heartbeat_proto_goTypes = nil
	file_internal_common_inner_protobuf_protomessages_heartbeat_proto_depIdxs = nil
}
