// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/common/inner/protobuf/protomessages/microtransaction.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Microtransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	ToAccount     string                 `protobuf:"bytes,2,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Microtransaction) Reset() {
	*x = Microtransaction{}
	mi := &file_internal_common_inner_protobuf_protomessages_microtransaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Microtransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Microtransaction) ProtoMessage() {}

func (x *Microtransaction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_protomessages_microtransaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Microtransaction.ProtoReflect.Descriptor instead.
func (*Microtransaction) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_protomessages_microtransaction_proto_rawDescGZIP(), []int{0}
}

func (x *Microtransaction) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Microtransaction) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *Microtransaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type MicrotransactionBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Microtransaction    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicrotransactionBatch) Reset() {
	*x = MicrotransactionBatch{}
	mi := &file_internal_common_inner_protobuf_protomessages_microtransaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicrotransactionBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicrotransactionBatch) ProtoMessage() {}

func (x *MicrotransactionBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_protomessages_microtransaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicrotransactionBatch.ProtoReflect.Descriptor instead.
func (*MicrotransactionBatch) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_protomessages_microtransaction_proto_rawDescGZIP(), []int{1}
}

func (x *MicrotransactionBatch) GetItems() []*Microtransaction {
	if x != nil {
		return x.Items
	}
	return nil
}

type MicrotransactionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Microtransaction    `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicrotransactionResult) Reset() {
	*x = MicrotransactionResult{}
	mi := &file_internal_common_inner_protobuf_protomessages_microtransaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicrotransactionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicrotransactionResult) ProtoMessage() {}

func (x *MicrotransactionResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_protomessages_microtransaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicrotransactionResult.ProtoReflect.Descriptor instead.
func (*MicrotransactionResult) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_protomessages_microtransaction_proto_rawDescGZIP(), []int{2}
}

func (x *MicrotransactionResult) GetTransactions() []*Microtransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_internal_common_inner_protobuf_protomessages_microtransaction_proto protoreflect.FileDescriptor

const file_internal_common_inner_protobuf_protomessages_microtransaction_proto_rawDesc = "" +
	"\n" +
	"Cinternal/common/inner/protobuf/protomessages/microtransaction.proto\x12\bprotobuf\"c\n" +
	"\x10Microtransaction\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1d\n" +
	"\n" +
	"to_account\x18\x02 \x01(\tR\ttoAccount\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"I\n" +
	"\x15MicrotransactionBatch\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.protobuf.MicrotransactionR\x05items\"X\n" +
	"\x16MicrotransactionResult\x12>\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1a.protobuf.MicrotransactionR\ftransactionsB1Z/tp-lavado-dinero/internal/common/inner/protobufb\x06proto3"

var (
	file_internal_common_inner_protobuf_protomessages_microtransaction_proto_rawDescOnce sync.Once
	file_internal_common_inner_protobuf_protomessages_microtransaction_proto_rawDescData []byte
)

func file_internal_common_inner_protobuf_protomessages_microtransaction_proto_rawDescGZIP() []byte {
	file_internal_common_inner_protobuf_protomessages_microtransaction_proto_rawDescOnce.Do(func() {
		file_internal_common_inner_protobuf_protomessages_microtransaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_protomessages_microtransaction_proto_rawDesc), len(file_internal_common_inner_protobuf_protomessages_microtransaction_proto_rawDesc)))
	})
	return file_internal_common_inner_protobuf_protomessages_microtransaction_proto_rawDescData
}

var file_internal_common_inner_protobuf_protomessages_microtransaction_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_common_inner_protobuf_protomessages_microtransaction_proto_goTypes = []any{
	(*Microtransaction)(nil),       // 0: protobuf.Microtransaction
	(*MicrotransactionBatch)(nil),  // 1: protobuf.MicrotransactionBatch
	(*MicrotransactionResult)(nil), // 2: protobuf.MicrotransactionResult
}
var file_internal_common_inner_protobuf_protomessages_microtransaction_proto_depIdxs = []int32{
	0, // 0: protobuf.MicrotransactionBatch.items:type_name -> protobuf.Microtransaction
	0, // 1: protobuf.MicrotransactionResult.transactions:type_name -> protobuf.Microtransaction
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_common_inner_protobuf_protomessages_microtransaction_proto_init() }
func file_internal_common_inner_protobuf_protomessages_microtransaction_proto_init() {
	if File_internal_common_inner_protobuf_protomessages_microtransaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_protomessages_microtransaction_proto_rawDesc), len(file_internal_common_inner_protobuf_protomessages_microtransaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_common_inner_protobuf_protomessages_microtransaction_proto_goTypes,
		DependencyIndexes: file_internal_common_inner_protobuf_protomessages_microtransaction_proto_depIdxs,
		MessageInfos:      file_internal_common_inner_protobuf_protomessages_microtransaction_proto_msgTypes,
	}.Build()
	File_internal_common_inner_protobuf_protomessages_microtransaction_proto = out.File
	file_internal_common_inner_protobuf_protomessages_microtransaction_proto_goTypes = nil
	file_internal_common_inner_protobuf_protomessages_microtransaction_proto_depIdxs = nil
}
