// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/common/inner/protobuf/protomessages/moneylaundry.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_EOF_                                   MessageType = 0
	MessageType_TRANSACTION                            MessageType = 1
	MessageType_MICROTRANSACTION                       MessageType = 2
	MessageType_MAXBANK                                MessageType = 3
	MessageType_PERIODFILTER                           MessageType = 4
	MessageType_SCATTERGATHER                          MessageType = 5
	MessageType_GROUPED_ACCOUNTS_BATCH                 MessageType = 6
	MessageType_INTERMEDIARYPAIR                       MessageType = 7
	MessageType_AVGBYTYPETRANSACTION                   MessageType = 8
	MessageType_TO_CONVERT_TRANSACTION                 MessageType = 9
	MessageType_TO_CONVERT_PERIOD_FILTERED             MessageType = 10
	MessageType_TO_CONVERT_TYPE_FILTERED_PAYMENT       MessageType = 11
	MessageType_CONVERTED_AMOUNT                       MessageType = 12
	MessageType_MICROTRANSACTION_RESULT                MessageType = 13
	MessageType_MAXBANK_RESULT                         MessageType = 14
	MessageType_CONVERTED_MICRO_PAYMENT_RESULT         MessageType = 15
	MessageType_AVGBYTYPE_RESULT                       MessageType = 16
	MessageType_AVGBYTYPE_FIRST_PERIOD                 MessageType = 17
	MessageType_AVGBYTYPE_SECOND_PERIOD                MessageType = 18
	MessageType_TRANSACTION_BATCH                      MessageType = 19
	MessageType_TO_CONVERT_TRANSACTION_BATCH           MessageType = 20
	MessageType_SUSPICIOUS_PATH_BATCH                  MessageType = 21
	MessageType_SUSPICIOUS_ACCOUNT_BATCH               MessageType = 22
	MessageType_MAXBANK_BATCH                          MessageType = 23
	MessageType_TO_CONVERT_PERIOD_FILTERED_BATCH       MessageType = 24
	MessageType_TO_CONVERT_TYPE_FILTERED_PAYMENT_BATCH MessageType = 25
	MessageType_CONVERTED_AMOUNT_BATCH                 MessageType = 26
	MessageType_MICROTRANSACTION_BATCH                 MessageType = 27
	MessageType_PERIOD_FILTER_BATCH                    MessageType = 28
	MessageType_CLEANUP                                MessageType = 29
	MessageType_AVGBYTYPE_TRANSACTION_BATCH            MessageType = 30
	MessageType_AVGBYTYPE_RESULT_BATCH                 MessageType = 31
	MessageType_SCATTERGATHER_BATCH                    MessageType = 32
	MessageType_INTERMEDIARYPAIR_BATCH                 MessageType = 33
	MessageType_MAX_BANK_RESULT_BATCH                  MessageType = 34
	MessageType_HEARTBEAT                              MessageType = 35
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "EOF_",
		1:  "TRANSACTION",
		2:  "MICROTRANSACTION",
		3:  "MAXBANK",
		4:  "PERIODFILTER",
		5:  "SCATTERGATHER",
		6:  "GROUPED_ACCOUNTS_BATCH",
		7:  "INTERMEDIARYPAIR",
		8:  "AVGBYTYPETRANSACTION",
		9:  "TO_CONVERT_TRANSACTION",
		10: "TO_CONVERT_PERIOD_FILTERED",
		11: "TO_CONVERT_TYPE_FILTERED_PAYMENT",
		12: "CONVERTED_AMOUNT",
		13: "MICROTRANSACTION_RESULT",
		14: "MAXBANK_RESULT",
		15: "CONVERTED_MICRO_PAYMENT_RESULT",
		16: "AVGBYTYPE_RESULT",
		17: "AVGBYTYPE_FIRST_PERIOD",
		18: "AVGBYTYPE_SECOND_PERIOD",
		19: "TRANSACTION_BATCH",
		20: "TO_CONVERT_TRANSACTION_BATCH",
		21: "SUSPICIOUS_PATH_BATCH",
		22: "SUSPICIOUS_ACCOUNT_BATCH",
		23: "MAXBANK_BATCH",
		24: "TO_CONVERT_PERIOD_FILTERED_BATCH",
		25: "TO_CONVERT_TYPE_FILTERED_PAYMENT_BATCH",
		26: "CONVERTED_AMOUNT_BATCH",
		27: "MICROTRANSACTION_BATCH",
		28: "PERIOD_FILTER_BATCH",
		29: "CLEANUP",
		30: "AVGBYTYPE_TRANSACTION_BATCH",
		31: "AVGBYTYPE_RESULT_BATCH",
		32: "SCATTERGATHER_BATCH",
		33: "INTERMEDIARYPAIR_BATCH",
		34: "MAX_BANK_RESULT_BATCH",
		35: "HEARTBEAT",
	}
	MessageType_value = map[string]int32{
		"EOF_":                                   0,
		"TRANSACTION":                            1,
		"MICROTRANSACTION":                       2,
		"MAXBANK":                                3,
		"PERIODFILTER":                           4,
		"SCATTERGATHER":                          5,
		"GROUPED_ACCOUNTS_BATCH":                 6,
		"INTERMEDIARYPAIR":                       7,
		"AVGBYTYPETRANSACTION":                   8,
		"TO_CONVERT_TRANSACTION":                 9,
		"TO_CONVERT_PERIOD_FILTERED":             10,
		"TO_CONVERT_TYPE_FILTERED_PAYMENT":       11,
		"CONVERTED_AMOUNT":                       12,
		"MICROTRANSACTION_RESULT":                13,
		"MAXBANK_RESULT":                         14,
		"CONVERTED_MICRO_PAYMENT_RESULT":         15,
		"AVGBYTYPE_RESULT":                       16,
		"AVGBYTYPE_FIRST_PERIOD":                 17,
		"AVGBYTYPE_SECOND_PERIOD":                18,
		"TRANSACTION_BATCH":                      19,
		"TO_CONVERT_TRANSACTION_BATCH":           20,
		"SUSPICIOUS_PATH_BATCH":                  21,
		"SUSPICIOUS_ACCOUNT_BATCH":               22,
		"MAXBANK_BATCH":                          23,
		"TO_CONVERT_PERIOD_FILTERED_BATCH":       24,
		"TO_CONVERT_TYPE_FILTERED_PAYMENT_BATCH": 25,
		"CONVERTED_AMOUNT_BATCH":                 26,
		"MICROTRANSACTION_BATCH":                 27,
		"PERIOD_FILTER_BATCH":                    28,
		"CLEANUP":                                29,
		"AVGBYTYPE_TRANSACTION_BATCH":            30,
		"AVGBYTYPE_RESULT_BATCH":                 31,
		"SCATTERGATHER_BATCH":                    32,
		"INTERMEDIARYPAIR_BATCH":                 33,
		"MAX_BANK_RESULT_BATCH":                  34,
		"HEARTBEAT":                              35,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_rawDescGZIP(), []int{0}
}

type MoneyLaundry struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ClientID string                 `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	Type     MessageType            `protobuf:"varint,2,opt,name=type,proto3,enum=protobuf.MessageType" json:"type,omitempty"`
	Payload  []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Se ingresa oneof aparte para que coexista con el resto del sistema
	// la idea es eliminar payload para obtimizar la serializacion
	//
	// Types that are valid to be assigned to InnerMessage:
	//
	//	*MoneyLaundry_Transactions
	//	*MoneyLaundry_ToConvertBatch
	//	*MoneyLaundry_EofMessage
	//	*MoneyLaundry_MaxBankBatch
	//	*MoneyLaundry_ToConvertPeriodFilteredBatch
	//	*MoneyLaundry_ToConvertTypeFilteredPaymentBatch
	//	*MoneyLaundry_ConvertedAmountBatch
	//	*MoneyLaundry_MicrotransactionsBatch
	//	*MoneyLaundry_PeriodFilterBatch
	//	*MoneyLaundry_AvgbytypeTransactionBatch
	//	*MoneyLaundry_ScattergatherBatch
	//	*MoneyLaundry_IntermediarypairBatch
	//	*MoneyLaundry_MaxBankResultBatch
	//	*MoneyLaundry_Heartbeat
	//	*MoneyLaundry_GroupedAccountsBatch
	//	*MoneyLaundry_AvgbytypeResultBatch
	//	*MoneyLaundry_SuspiciouspathBatch
	InnerMessage  isMoneyLaundry_InnerMessage `protobuf_oneof:"inner_message"`
	BatchID       string                      `protobuf:"bytes,21,opt,name=batchID,proto3" json:"batchID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoneyLaundry) Reset() {
	*x = MoneyLaundry{}
	mi := &file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoneyLaundry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoneyLaundry) ProtoMessage() {}

func (x *MoneyLaundry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoneyLaundry.ProtoReflect.Descriptor instead.
func (*MoneyLaundry) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_rawDescGZIP(), []int{0}
}

func (x *MoneyLaundry) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *MoneyLaundry) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_EOF_
}

func (x *MoneyLaundry) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MoneyLaundry) GetInnerMessage() isMoneyLaundry_InnerMessage {
	if x != nil {
		return x.InnerMessage
	}
	return nil
}

func (x *MoneyLaundry) GetTransactions() *TransactionBatch {
	if x != nil {
		if x, ok := x.InnerMessage.(*MoneyLaundry_Transactions); ok {
			return x.Transactions
		}
	}
	return nil
}

func (x *MoneyLaundry) GetToConvertBatch() *ToConvertTransactionBatch {
	if x != nil {
		if x, ok := x.InnerMessage.(*MoneyLaundry_ToConvertBatch); ok {
			return x.ToConvertBatch
		}
	}
	return nil
}

func (x *MoneyLaundry) GetEofMessage() *EOF {
	if x != nil {
		if x, ok := x.InnerMessage.(*MoneyLaundry_EofMessage); ok {
			return x.EofMessage
		}
	}
	return nil
}

func (x *MoneyLaundry) GetMaxBankBatch() *MaxBankBatch {
	if x != nil {
		if x, ok := x.InnerMessage.(*MoneyLaundry_MaxBankBatch); ok {
			return x.MaxBankBatch
		}
	}
	return nil
}

func (x *MoneyLaundry) GetToConvertPeriodFilteredBatch() *ToConvertPeriodFilteredBatch {
	if x != nil {
		if x, ok := x.InnerMessage.(*MoneyLaundry_ToConvertPeriodFilteredBatch); ok {
			return x.ToConvertPeriodFilteredBatch
		}
	}
	return nil
}

func (x *MoneyLaundry) GetToConvertTypeFilteredPaymentBatch() *ToConvertTypeFilteredPaymentBatch {
	if x != nil {
		if x, ok := x.InnerMessage.(*MoneyLaundry_ToConvertTypeFilteredPaymentBatch); ok {
			return x.ToConvertTypeFilteredPaymentBatch
		}
	}
	return nil
}

func (x *MoneyLaundry) GetConvertedAmountBatch() *ConvertedAmountBatch {
	if x != nil {
		if x, ok := x.InnerMessage.(*MoneyLaundry_ConvertedAmountBatch); ok {
			return x.ConvertedAmountBatch
		}
	}
	return nil
}

func (x *MoneyLaundry) GetMicrotransactionsBatch() *MicrotransactionBatch {
	if x != nil {
		if x, ok := x.InnerMessage.(*MoneyLaundry_MicrotransactionsBatch); ok {
			return x.MicrotransactionsBatch
		}
	}
	return nil
}

func (x *MoneyLaundry) GetPeriodFilterBatch() *PeriodFilterBatch {
	if x != nil {
		if x, ok := x.InnerMessage.(*MoneyLaundry_PeriodFilterBatch); ok {
			return x.PeriodFilterBatch
		}
	}
	return nil
}

func (x *MoneyLaundry) GetAvgbytypeTransactionBatch() *AvgByTypeTransactionBatch {
	if x != nil {
		if x, ok := x.InnerMessage.(*MoneyLaundry_AvgbytypeTransactionBatch); ok {
			return x.AvgbytypeTransactionBatch
		}
	}
	return nil
}

func (x *MoneyLaundry) GetScattergatherBatch() *ScatterGatherBatch {
	if x != nil {
		if x, ok := x.InnerMessage.(*MoneyLaundry_ScattergatherBatch); ok {
			return x.ScattergatherBatch
		}
	}
	return nil
}

func (x *MoneyLaundry) GetIntermediarypairBatch() *IntermediaryPairBatch {
	if x != nil {
		if x, ok := x.InnerMessage.(*MoneyLaundry_IntermediarypairBatch); ok {
			return x.IntermediarypairBatch
		}
	}
	return nil
}

func (x *MoneyLaundry) GetMaxBankResultBatch() *MaxBankResultBatch {
	if x != nil {
		if x, ok := x.InnerMessage.(*MoneyLaundry_MaxBankResultBatch); ok {
			return x.MaxBankResultBatch
		}
	}
	return nil
}

func (x *MoneyLaundry) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.InnerMessage.(*MoneyLaundry_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *MoneyLaundry) GetGroupedAccountsBatch() *GroupedAccountsBatch {
	if x != nil {
		if x, ok := x.InnerMessage.(*MoneyLaundry_GroupedAccountsBatch); ok {
			return x.GroupedAccountsBatch
		}
	}
	return nil
}

func (x *MoneyLaundry) GetAvgbytypeResultBatch() *AvgByTypeResultBatch {
	if x != nil {
		if x, ok := x.InnerMessage.(*MoneyLaundry_AvgbytypeResultBatch); ok {
			return x.AvgbytypeResultBatch
		}
	}
	return nil
}

func (x *MoneyLaundry) GetSuspiciouspathBatch() *SuspiciousPathBatch {
	if x != nil {
		if x, ok := x.InnerMessage.(*MoneyLaundry_SuspiciouspathBatch); ok {
			return x.SuspiciouspathBatch
		}
	}
	return nil
}

func (x *MoneyLaundry) GetBatchID() string {
	if x != nil {
		return x.BatchID
	}
	return ""
}

type isMoneyLaundry_InnerMessage interface {
	isMoneyLaundry_InnerMessage()
}

type MoneyLaundry_Transactions struct {
	Transactions *TransactionBatch `protobuf:"bytes,4,opt,name=transactions,proto3,oneof"`
}

type MoneyLaundry_ToConvertBatch struct {
	ToConvertBatch *ToConvertTransactionBatch `protobuf:"bytes,5,opt,name=to_convert_batch,json=toConvertBatch,proto3,oneof"`
}

type MoneyLaundry_EofMessage struct {
	EofMessage *EOF `protobuf:"bytes,6,opt,name=eof_message,json=eofMessage,proto3,oneof"`
}

type MoneyLaundry_MaxBankBatch struct {
	MaxBankBatch *MaxBankBatch `protobuf:"bytes,7,opt,name=max_bank_batch,json=maxBankBatch,proto3,oneof"`
}

type MoneyLaundry_ToConvertPeriodFilteredBatch struct {
	ToConvertPeriodFilteredBatch *ToConvertPeriodFilteredBatch `protobuf:"bytes,8,opt,name=to_convert_period_filtered_batch,json=toConvertPeriodFilteredBatch,proto3,oneof"`
}

type MoneyLaundry_ToConvertTypeFilteredPaymentBatch struct {
	ToConvertTypeFilteredPaymentBatch *ToConvertTypeFilteredPaymentBatch `protobuf:"bytes,9,opt,name=to_convert_type_filtered_payment_batch,json=toConvertTypeFilteredPaymentBatch,proto3,oneof"`
}

type MoneyLaundry_ConvertedAmountBatch struct {
	ConvertedAmountBatch *ConvertedAmountBatch `protobuf:"bytes,10,opt,name=converted_amount_batch,json=convertedAmountBatch,proto3,oneof"`
}

type MoneyLaundry_MicrotransactionsBatch struct {
	MicrotransactionsBatch *MicrotransactionBatch `protobuf:"bytes,11,opt,name=microtransactions_batch,json=microtransactionsBatch,proto3,oneof"`
}

type MoneyLaundry_PeriodFilterBatch struct {
	PeriodFilterBatch *PeriodFilterBatch `protobuf:"bytes,12,opt,name=period_filter_batch,json=periodFilterBatch,proto3,oneof"`
}

type MoneyLaundry_AvgbytypeTransactionBatch struct {
	AvgbytypeTransactionBatch *AvgByTypeTransactionBatch `protobuf:"bytes,13,opt,name=avgbytype_transaction_batch,json=avgbytypeTransactionBatch,proto3,oneof"`
}

type MoneyLaundry_ScattergatherBatch struct {
	ScattergatherBatch *ScatterGatherBatch `protobuf:"bytes,14,opt,name=scattergather_batch,json=scattergatherBatch,proto3,oneof"`
}

type MoneyLaundry_IntermediarypairBatch struct {
	IntermediarypairBatch *IntermediaryPairBatch `protobuf:"bytes,15,opt,name=intermediarypair_batch,json=intermediarypairBatch,proto3,oneof"`
}

type MoneyLaundry_MaxBankResultBatch struct {
	MaxBankResultBatch *MaxBankResultBatch `protobuf:"bytes,16,opt,name=max_bank_result_batch,json=maxBankResultBatch,proto3,oneof"`
}

type MoneyLaundry_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,17,opt,name=heartbeat,proto3,oneof"`
}

type MoneyLaundry_GroupedAccountsBatch struct {
	GroupedAccountsBatch *GroupedAccountsBatch `protobuf:"bytes,18,opt,name=grouped_accounts_batch,json=groupedAccountsBatch,proto3,oneof"`
}

type MoneyLaundry_AvgbytypeResultBatch struct {
	AvgbytypeResultBatch *AvgByTypeResultBatch `protobuf:"bytes,19,opt,name=avgbytype_result_batch,json=avgbytypeResultBatch,proto3,oneof"`
}

type MoneyLaundry_SuspiciouspathBatch struct {
	SuspiciouspathBatch *SuspiciousPathBatch `protobuf:"bytes,20,opt,name=suspiciouspath_batch,json=suspiciouspathBatch,proto3,oneof"`
}

func (*MoneyLaundry_Transactions) isMoneyLaundry_InnerMessage() {}

func (*MoneyLaundry_ToConvertBatch) isMoneyLaundry_InnerMessage() {}

func (*MoneyLaundry_EofMessage) isMoneyLaundry_InnerMessage() {}

func (*MoneyLaundry_MaxBankBatch) isMoneyLaundry_InnerMessage() {}

func (*MoneyLaundry_ToConvertPeriodFilteredBatch) isMoneyLaundry_InnerMessage() {}

func (*MoneyLaundry_ToConvertTypeFilteredPaymentBatch) isMoneyLaundry_InnerMessage() {}

func (*MoneyLaundry_ConvertedAmountBatch) isMoneyLaundry_InnerMessage() {}

func (*MoneyLaundry_MicrotransactionsBatch) isMoneyLaundry_InnerMessage() {}

func (*MoneyLaundry_PeriodFilterBatch) isMoneyLaundry_InnerMessage() {}

func (*MoneyLaundry_AvgbytypeTransactionBatch) isMoneyLaundry_InnerMessage() {}

func (*MoneyLaundry_ScattergatherBatch) isMoneyLaundry_InnerMessage() {}

func (*MoneyLaundry_IntermediarypairBatch) isMoneyLaundry_InnerMessage() {}

func (*MoneyLaundry_MaxBankResultBatch) isMoneyLaundry_InnerMessage() {}

func (*MoneyLaundry_Heartbeat) isMoneyLaundry_InnerMessage() {}

func (*MoneyLaundry_GroupedAccountsBatch) isMoneyLaundry_InnerMessage() {}

func (*MoneyLaundry_AvgbytypeResultBatch) isMoneyLaundry_InnerMessage() {}

func (*MoneyLaundry_SuspiciouspathBatch) isMoneyLaundry_InnerMessage() {}

var File_internal_common_inner_protobuf_protomessages_moneylaundry_proto protoreflect.FileDescriptor

const file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_rawDesc = "" +
	"\n" +
	"?internal/common/inner/protobuf/protomessages/moneylaundry.proto\x12\bprotobuf\x1a>internal/common/inner/protobuf/protomessages/transaction.proto\x1a=internal/common/inner/protobuf/protomessages/conversion.proto\x1a6internal/common/inner/protobuf/protomessages/eof.proto\x1a:internal/common/inner/protobuf/protomessages/maxbank.proto\x1aCinternal/common/inner/protobuf/protomessages/microtransaction.proto\x1a?internal/common/inner/protobuf/protomessages/periodfilter.proto\x1aGinternal/common/inner/protobuf/protomessages/avgbytypetransaction.proto\x1a@internal/common/inner/protobuf/protomessages/scattergather.proto\x1aCinternal/common/inner/protobuf/protomessages/intermediarypair.proto\x1a<internal/common/inner/protobuf/protomessages/heartbeat.proto\x1aGinternal/common/inner/protobuf/protomessages/groupedaccountsbatch.proto\x1aBinternal/common/inner/protobuf/protomessages/avgbytyperesult.proto\x1aAinternal/common/inner/protobuf/protomessages/suspiciouspath.proto\"\xb5\f\n" +
	"\fMoneyLaundry\x12\x1a\n" +
	"\bclientID\x18\x01 \x01(\tR\bclientID\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.protobuf.MessageTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12@\n" +
	"\ftransactions\x18\x04 \x01(\v2\x1a.protobuf.TransactionBatchH\x00R\ftransactions\x12O\n" +
	"\x10to_convert_batch\x18\x05 \x01(\v2#.protobuf.ToConvertTransactionBatchH\x00R\x0etoConvertBatch\x120\n" +
	"\veof_message\x18\x06 \x01(\v2\r.protobuf.EOFH\x00R\n" +
	"eofMessage\x12>\n" +
	"\x0emax_bank_batch\x18\a \x01(\v2\x16.protobuf.MaxBankBatchH\x00R\fmaxBankBatch\x12p\n" +
	" to_convert_period_filtered_batch\x18\b \x01(\v2&.protobuf.ToConvertPeriodFilteredBatchH\x00R\x1ctoConvertPeriodFilteredBatch\x12\x80\x01\n" +
	"&to_convert_type_filtered_payment_batch\x18\t \x01(\v2+.protobuf.ToConvertTypeFilteredPaymentBatchH\x00R!toConvertTypeFilteredPaymentBatch\x12V\n" +
	"\x16converted_amount_batch\x18\n" +
	" \x01(\v2\x1e.protobuf.ConvertedAmountBatchH\x00R\x14convertedAmountBatch\x12Z\n" +
	"\x17microtransactions_batch\x18\v \x01(\v2\x1f.protobuf.MicrotransactionBatchH\x00R\x16microtransactionsBatch\x12M\n" +
	"\x13period_filter_batch\x18\f \x01(\v2\x1b.protobuf.PeriodFilterBatchH\x00R\x11periodFilterBatch\x12e\n" +
	"\x1bavgbytype_transaction_batch\x18\r \x01(\v2#.protobuf.AvgByTypeTransactionBatchH\x00R\x19avgbytypeTransactionBatch\x12O\n" +
	"\x13scattergather_batch\x18\x0e \x01(\v2\x1c.protobuf.ScatterGatherBatchH\x00R\x12scattergatherBatch\x12X\n" +
	"\x16intermediarypair_batch\x18\x0f \x01(\v2\x1f.protobuf.IntermediaryPairBatchH\x00R\x15intermediarypairBatch\x12Q\n" +
	"\x15max_bank_result_batch\x18\x10 \x01(\v2\x1c.protobuf.MaxBankResultBatchH\x00R\x12maxBankResultBatch\x123\n" +
	"\theartbeat\x18\x11 \x01(\v2\x13.protobuf.HeartbeatH\x00R\theartbeat\x12V\n" +
	"\x16grouped_accounts_batch\x18\x12 \x01(\v2\x1e.protobuf.GroupedAccountsBatchH\x00R\x14groupedAccountsBatch\x12V\n" +
	"\x16avgbytype_result_batch\x18\x13 \x01(\v2\x1e.protobuf.AvgByTypeResultBatchH\x00R\x14avgbytypeResultBatch\x12R\n" +
	"\x14suspiciouspath_batch\x18\x14 \x01(\v2\x1d.protobuf.SuspiciousPathBatchH\x00R\x13suspiciouspathBatch\x12\x18\n" +
	"\abatchID\x18\x15 \x01(\tR\abatchIDB\x0f\n" +
	"\rinner_message*\xa9\a\n" +
	"\vMessageType\x12\b\n" +
	"\x04EOF_\x10\x00\x12\x0f\n" +
	"\vTRANSACTION\x10\x01\x12\x14\n" +
	"\x10MICROTRANSACTION\x10\x02\x12\v\n" +
	"\aMAXBANK\x10\x03\x12\x10\n" +
	"\fPERIODFILTER\x10\x04\x12\x11\n" +
	"\rSCATTERGATHER\x10\x05\x12\x1a\n" +
	"\x16GROUPED_ACCOUNTS_BATCH\x10\x06\x12\x14\n" +
	"\x10INTERMEDIARYPAIR\x10\a\x12\x18\n" +
	"\x14AVGBYTYPETRANSACTION\x10\b\x12\x1a\n" +
	"\x16TO_CONVERT_TRANSACTION\x10\t\x12\x1e\n" +
	"\x1aTO_CONVERT_PERIOD_FILTERED\x10\n" +
	"\x12$\n" +
	" TO_CONVERT_TYPE_FILTERED_PAYMENT\x10\v\x12\x14\n" +
	"\x10CONVERTED_AMOUNT\x10\f\x12\x1b\n" +
	"\x17MICROTRANSACTION_RESULT\x10\r\x12\x12\n" +
	"\x0eMAXBANK_RESULT\x10\x0e\x12\"\n" +
	"\x1eCONVERTED_MICRO_PAYMENT_RESULT\x10\x0f\x12\x14\n" +
	"\x10AVGBYTYPE_RESULT\x10\x10\x12\x1a\n" +
	"\x16AVGBYTYPE_FIRST_PERIOD\x10\x11\x12\x1b\n" +
	"\x17AVGBYTYPE_SECOND_PERIOD\x10\x12\x12\x15\n" +
	"\x11TRANSACTION_BATCH\x10\x13\x12 \n" +
	"\x1cTO_CONVERT_TRANSACTION_BATCH\x10\x14\x12\x19\n" +
	"\x15SUSPICIOUS_PATH_BATCH\x10\x15\x12\x1c\n" +
	"\x18SUSPICIOUS_ACCOUNT_BATCH\x10\x16\x12\x11\n" +
	"\rMAXBANK_BATCH\x10\x17\x12$\n" +
	" TO_CONVERT_PERIOD_FILTERED_BATCH\x10\x18\x12*\n" +
	"&TO_CONVERT_TYPE_FILTERED_PAYMENT_BATCH\x10\x19\x12\x1a\n" +
	"\x16CONVERTED_AMOUNT_BATCH\x10\x1a\x12\x1a\n" +
	"\x16MICROTRANSACTION_BATCH\x10\x1b\x12\x17\n" +
	"\x13PERIOD_FILTER_BATCH\x10\x1c\x12\v\n" +
	"\aCLEANUP\x10\x1d\x12\x1f\n" +
	"\x1bAVGBYTYPE_TRANSACTION_BATCH\x10\x1e\x12\x1a\n" +
	"\x16AVGBYTYPE_RESULT_BATCH\x10\x1f\x12\x17\n" +
	"\x13SCATTERGATHER_BATCH\x10 \x12\x1a\n" +
	"\x16INTERMEDIARYPAIR_BATCH\x10!\x12\x19\n" +
	"\x15MAX_BANK_RESULT_BATCH\x10\"\x12\r\n" +
	"\tHEARTBEAT\x10#B1Z/tp-lavado-dinero/internal/common/inner/protobufb\x06proto3"

var (
	file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_rawDescOnce sync.Once
	file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_rawDescData []byte
)

func file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_rawDescGZIP() []byte {
	file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_rawDescOnce.Do(func() {
		file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_rawDesc), len(file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_rawDesc)))
	})
	return file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_rawDescData
}

var file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_goTypes = []any{
	(MessageType)(0),                          // 0: protobuf.MessageType
	(*MoneyLaundry)(nil),                      // 1: protobuf.MoneyLaundry
	(*TransactionBatch)(nil),                  // 2: protobuf.TransactionBatch
	(*ToConvertTransactionBatch)(nil),         // 3: protobuf.ToConvertTransactionBatch
	(*EOF)(nil),                               // 4: protobuf.EOF
	(*MaxBankBatch)(nil),                      // 5: protobuf.MaxBankBatch
	(*ToConvertPeriodFilteredBatch)(nil),      // 6: protobuf.ToConvertPeriodFilteredBatch
	(*ToConvertTypeFilteredPaymentBatch)(nil), // 7: protobuf.ToConvertTypeFilteredPaymentBatch
	(*ConvertedAmountBatch)(nil),              // 8: protobuf.ConvertedAmountBatch
	(*MicrotransactionBatch)(nil),             // 9: protobuf.MicrotransactionBatch
	(*PeriodFilterBatch)(nil),                 // 10: protobuf.PeriodFilterBatch
	(*AvgByTypeTransactionBatch)(nil),         // 11: protobuf.AvgByTypeTransactionBatch
	(*ScatterGatherBatch)(nil),                // 12: protobuf.ScatterGatherBatch
	(*IntermediaryPairBatch)(nil),             // 13: protobuf.IntermediaryPairBatch
	(*MaxBankResultBatch)(nil),                // 14: protobuf.MaxBankResultBatch
	(*Heartbeat)(nil),                         // 15: protobuf.Heartbeat
	(*GroupedAccountsBatch)(nil),              // 16: protobuf.GroupedAccountsBatch
	(*AvgByTypeResultBatch)(nil),              // 17: protobuf.AvgByTypeResultBatch
	(*SuspiciousPathBatch)(nil),               // 18: protobuf.SuspiciousPathBatch
}
var file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_depIdxs = []int32{
	0,  // 0: protobuf.MoneyLaundry.type:type_name -> protobuf.MessageType
	2,  // 1: protobuf.MoneyLaundry.transactions:type_name -> protobuf.TransactionBatch
	3,  // 2: protobuf.MoneyLaundry.to_convert_batch:type_name -> protobuf.ToConvertTransactionBatch
	4,  // 3: protobuf.MoneyLaundry.eof_message:type_name -> protobuf.EOF
	5,  // 4: protobuf.MoneyLaundry.max_bank_batch:type_name -> protobuf.MaxBankBatch
	6,  // 5: protobuf.MoneyLaundry.to_convert_period_filtered_batch:type_name -> protobuf.ToConvertPeriodFilteredBatch
	7,  // 6: protobuf.MoneyLaundry.to_convert_type_filtered_payment_batch:type_name -> protobuf.ToConvertTypeFilteredPaymentBatch
	8,  // 7: protobuf.MoneyLaundry.converted_amount_batch:type_name -> protobuf.ConvertedAmountBatch
	9,  // 8: protobuf.MoneyLaundry.microtransactions_batch:type_name -> protobuf.MicrotransactionBatch
	10, // 9: protobuf.MoneyLaundry.period_filter_batch:type_name -> protobuf.PeriodFilterBatch
	11, // 10: protobuf.MoneyLaundry.avgbytype_transaction_batch:type_name -> protobuf.AvgByTypeTransactionBatch
	12, // 11: protobuf.MoneyLaundry.scattergather_batch:type_name -> protobuf.ScatterGatherBatch
	13, // 12: protobuf.MoneyLaundry.intermediarypair_batch:type_name -> protobuf.IntermediaryPairBatch
	14, // 13: protobuf.MoneyLaundry.max_bank_result_batch:type_name -> protobuf.MaxBankResultBatch
	15, // 14: protobuf.MoneyLaundry.heartbeat:type_name -> protobuf.Heartbeat
	16, // 15: protobuf.MoneyLaundry.grouped_accounts_batch:type_name -> protobuf.GroupedAccountsBatch
	17, // 16: protobuf.MoneyLaundry.avgbytype_result_batch:type_name -> protobuf.AvgByTypeResultBatch
	18, // 17: protobuf.MoneyLaundry.suspiciouspath_batch:type_name -> protobuf.SuspiciousPathBatch
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_init() }
func file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_init() {
	if File_internal_common_inner_protobuf_protomessages_moneylaundry_proto != nil {
		return
	}
	file_internal_common_inner_protobuf_protomessages_transaction_proto_init()
	file_internal_common_inner_protobuf_protomessages_conversion_proto_init()
	file_internal_common_inner_protobuf_protomessages_eof_proto_init()
	file_internal_common_inner_protobuf_protomessages_maxbank_proto_init()
	file_internal_common_inner_protobuf_protomessages_microtransaction_proto_init()
	file_internal_common_inner_protobuf_protomessages_periodfilter_proto_init()
	file_internal_common_inner_protobuf_protomessages_avgbytypetransaction_proto_init()
	file_internal_common_inner_protobuf_protomessages_scattergather_proto_init()
	file_internal_common_inner_protobuf_protomessages_intermediarypair_proto_init()
	file_internal_common_inner_protobuf_protomessages_heartbeat_proto_init()
	file_internal_common_inner_protobuf_protomessages_groupedaccountsbatch_proto_init()
	file_internal_common_inner_protobuf_protomessages_avgbytyperesult_proto_init()
	file_internal_common_inner_protobuf_protomessages_suspiciouspath_proto_init()
	file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_msgTypes[0].OneofWrappers = []any{
		(*MoneyLaundry_Transactions)(nil),
		(*MoneyLaundry_ToConvertBatch)(nil),
		(*MoneyLaundry_EofMessage)(nil),
		(*MoneyLaundry_MaxBankBatch)(nil),
		(*MoneyLaundry_ToConvertPeriodFilteredBatch)(nil),
		(*MoneyLaundry_ToConvertTypeFilteredPaymentBatch)(nil),
		(*MoneyLaundry_ConvertedAmountBatch)(nil),
		(*MoneyLaundry_MicrotransactionsBatch)(nil),
		(*MoneyLaundry_PeriodFilterBatch)(nil),
		(*MoneyLaundry_AvgbytypeTransactionBatch)(nil),
		(*MoneyLaundry_ScattergatherBatch)(nil),
		(*MoneyLaundry_IntermediarypairBatch)(nil),
		(*MoneyLaundry_MaxBankResultBatch)(nil),
		(*MoneyLaundry_Heartbeat)(nil),
		(*MoneyLaundry_GroupedAccountsBatch)(nil),
		(*MoneyLaundry_AvgbytypeResultBatch)(nil),
		(*MoneyLaundry_SuspiciouspathBatch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_rawDesc), len(file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_goTypes,
		DependencyIndexes: file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_depIdxs,
		EnumInfos:         file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_enumTypes,
		MessageInfos:      file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_msgTypes,
	}.Build()
	File_internal_common_inner_protobuf_protomessages_moneylaundry_proto = out.File
	file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_goTypes = nil
	file_internal_common_inner_protobuf_protomessages_moneylaundry_proto_depIdxs = nil
}
