// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/common/inner/protobuf/protomessages/suspiciousaccount.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SuspiciousAccountBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspiciousAccountBatch) Reset() {
	*x = SuspiciousAccountBatch{}
	mi := &file_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspiciousAccountBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspiciousAccountBatch) ProtoMessage() {}

func (x *SuspiciousAccountBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspiciousAccountBatch.ProtoReflect.Descriptor instead.
func (*SuspiciousAccountBatch) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto_rawDescGZIP(), []int{0}
}

func (x *SuspiciousAccountBatch) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

var File_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto protoreflect.FileDescriptor

const file_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto_rawDesc = "" +
	"\n" +
	"Dinternal/common/inner/protobuf/protomessages/suspiciousaccount.proto\x12\bprotobuf\x1a:internal/common/inner/protobuf/protomessages/account.proto\"G\n" +
	"\x16SuspiciousAccountBatch\x12-\n" +
	"\baccounts\x18\x01 \x03(\v2\x11.protobuf.AccountR\baccountsB1Z/tp-lavado-dinero/internal/common/inner/protobufb\x06proto3"

var (
	file_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto_rawDescOnce sync.Once
	file_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto_rawDescData []byte
)

func file_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto_rawDescGZIP() []byte {
	file_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto_rawDescOnce.Do(func() {
		file_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto_rawDesc), len(file_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto_rawDesc)))
	})
	return file_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto_rawDescData
}

var file_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto_goTypes = []any{
	(*SuspiciousAccountBatch)(nil), // 0: protobuf.SuspiciousAccountBatch
	(*Account)(nil),                // 1: protobuf.Account
}
var file_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto_depIdxs = []int32{
	1, // 0: protobuf.SuspiciousAccountBatch.accounts:type_name -> protobuf.Account
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto_init() }
func file_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto_init() {
	if File_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto != nil {
		return
	}
	file_internal_common_inner_protobuf_protomessages_account_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto_rawDesc), len(file_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto_goTypes,
		DependencyIndexes: file_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto_depIdxs,
		MessageInfos:      file_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto_msgTypes,
	}.Build()
	File_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto = out.File
	file_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto_goTypes = nil
	file_internal_common_inner_protobuf_protomessages_suspiciousaccount_proto_depIdxs = nil
}
