// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/common/inner/protobuf/avgbytyperesult.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvgByTypeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	AmountPaid    string                 `protobuf:"bytes,2,opt,name=amount_paid,json=amountPaid,proto3" json:"amount_paid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvgByTypeResult) Reset() {
	*x = AvgByTypeResult{}
	mi := &file_internal_common_inner_protobuf_avgbytyperesult_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvgByTypeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvgByTypeResult) ProtoMessage() {}

func (x *AvgByTypeResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_avgbytyperesult_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvgByTypeResult.ProtoReflect.Descriptor instead.
func (*AvgByTypeResult) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_avgbytyperesult_proto_rawDescGZIP(), []int{0}
}

func (x *AvgByTypeResult) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AvgByTypeResult) GetAmountPaid() string {
	if x != nil {
		return x.AmountPaid
	}
	return ""
}

type AvgByTypeResultBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*AvgByTypeResult     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvgByTypeResultBatch) Reset() {
	*x = AvgByTypeResultBatch{}
	mi := &file_internal_common_inner_protobuf_avgbytyperesult_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvgByTypeResultBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvgByTypeResultBatch) ProtoMessage() {}

func (x *AvgByTypeResultBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_avgbytyperesult_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvgByTypeResultBatch.ProtoReflect.Descriptor instead.
func (*AvgByTypeResultBatch) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_avgbytyperesult_proto_rawDescGZIP(), []int{1}
}

func (x *AvgByTypeResultBatch) GetResults() []*AvgByTypeResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_internal_common_inner_protobuf_avgbytyperesult_proto protoreflect.FileDescriptor

const file_internal_common_inner_protobuf_avgbytyperesult_proto_rawDesc = "" +
	"\n" +
	"4internal/common/inner/protobuf/avgbytyperesult.proto\x12\bprotobuf\"L\n" +
	"\x0fAvgByTypeResult\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1f\n" +
	"\vamount_paid\x18\x02 \x01(\tR\n" +
	"amountPaid\"K\n" +
	"\x14AvgByTypeResultBatch\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.protobuf.AvgByTypeResultR\aresultsB1Z/tp-lavado-dinero/internal/common/inner/protobufb\x06proto3"

var (
	file_internal_common_inner_protobuf_avgbytyperesult_proto_rawDescOnce sync.Once
	file_internal_common_inner_protobuf_avgbytyperesult_proto_rawDescData []byte
)

func file_internal_common_inner_protobuf_avgbytyperesult_proto_rawDescGZIP() []byte {
	file_internal_common_inner_protobuf_avgbytyperesult_proto_rawDescOnce.Do(func() {
		file_internal_common_inner_protobuf_avgbytyperesult_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_avgbytyperesult_proto_rawDesc), len(file_internal_common_inner_protobuf_avgbytyperesult_proto_rawDesc)))
	})
	return file_internal_common_inner_protobuf_avgbytyperesult_proto_rawDescData
}

var file_internal_common_inner_protobuf_avgbytyperesult_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_common_inner_protobuf_avgbytyperesult_proto_goTypes = []any{
	(*AvgByTypeResult)(nil),      // 0: protobuf.AvgByTypeResult
	(*AvgByTypeResultBatch)(nil), // 1: protobuf.AvgByTypeResultBatch
}
var file_internal_common_inner_protobuf_avgbytyperesult_proto_depIdxs = []int32{
	0, // 0: protobuf.AvgByTypeResultBatch.results:type_name -> protobuf.AvgByTypeResult
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_common_inner_protobuf_avgbytyperesult_proto_init() }
func file_internal_common_inner_protobuf_avgbytyperesult_proto_init() {
	if File_internal_common_inner_protobuf_avgbytyperesult_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_avgbytyperesult_proto_rawDesc), len(file_internal_common_inner_protobuf_avgbytyperesult_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_common_inner_protobuf_avgbytyperesult_proto_goTypes,
		DependencyIndexes: file_internal_common_inner_protobuf_avgbytyperesult_proto_depIdxs,
		MessageInfos:      file_internal_common_inner_protobuf_avgbytyperesult_proto_msgTypes,
	}.Build()
	File_internal_common_inner_protobuf_avgbytyperesult_proto = out.File
	file_internal_common_inner_protobuf_avgbytyperesult_proto_goTypes = nil
	file_internal_common_inner_protobuf_avgbytyperesult_proto_depIdxs = nil
}
