// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/common/inner/protobuf/avgbytypetransaction.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvgByTypeTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	AmountPaid    string                 `protobuf:"bytes,2,opt,name=amount_paid,json=amountPaid,proto3" json:"amount_paid,omitempty"`
	PaymentFormat string                 `protobuf:"bytes,3,opt,name=payment_format,json=paymentFormat,proto3" json:"payment_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvgByTypeTransaction) Reset() {
	*x = AvgByTypeTransaction{}
	mi := &file_internal_common_inner_protobuf_avgbytypetransaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvgByTypeTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvgByTypeTransaction) ProtoMessage() {}

func (x *AvgByTypeTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_avgbytypetransaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvgByTypeTransaction.ProtoReflect.Descriptor instead.
func (*AvgByTypeTransaction) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDescGZIP(), []int{0}
}

func (x *AvgByTypeTransaction) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AvgByTypeTransaction) GetAmountPaid() string {
	if x != nil {
		return x.AmountPaid
	}
	return ""
}

func (x *AvgByTypeTransaction) GetPaymentFormat() string {
	if x != nil {
		return x.PaymentFormat
	}
	return ""
}

var File_internal_common_inner_protobuf_avgbytypetransaction_proto protoreflect.FileDescriptor

const file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDesc = "" +
	"\n" +
	"9internal/common/inner/protobuf/avgbytypetransaction.proto\x12\bprotobuf\"x\n" +
	"\x14AvgByTypeTransaction\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1f\n" +
	"\vamount_paid\x18\x02 \x01(\tR\n" +
	"amountPaid\x12%\n" +
	"\x0epayment_format\x18\x03 \x01(\tR\rpaymentFormatB1Z/tp-lavado-dinero/internal/common/inner/protobufb\x06proto3"

var (
	file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDescOnce sync.Once
	file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDescData []byte
)

func file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDescGZIP() []byte {
	file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDescOnce.Do(func() {
		file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDesc), len(file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDesc)))
	})
	return file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDescData
}

var file_internal_common_inner_protobuf_avgbytypetransaction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_common_inner_protobuf_avgbytypetransaction_proto_goTypes = []any{
	(*AvgByTypeTransaction)(nil), // 0: protobuf.AvgByTypeTransaction
}
var file_internal_common_inner_protobuf_avgbytypetransaction_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_common_inner_protobuf_avgbytypetransaction_proto_init() }
func file_internal_common_inner_protobuf_avgbytypetransaction_proto_init() {
	if File_internal_common_inner_protobuf_avgbytypetransaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDesc), len(file_internal_common_inner_protobuf_avgbytypetransaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_common_inner_protobuf_avgbytypetransaction_proto_goTypes,
		DependencyIndexes: file_internal_common_inner_protobuf_avgbytypetransaction_proto_depIdxs,
		MessageInfos:      file_internal_common_inner_protobuf_avgbytypetransaction_proto_msgTypes,
	}.Build()
	File_internal_common_inner_protobuf_avgbytypetransaction_proto = out.File
	file_internal_common_inner_protobuf_avgbytypetransaction_proto_goTypes = nil
	file_internal_common_inner_protobuf_avgbytypetransaction_proto_depIdxs = nil
}
