// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/common/inner/protobuf/conversion.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ToConvertTransaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AmountPaid      string                 `protobuf:"bytes,2,opt,name=amount_paid,json=amountPaid,proto3" json:"amount_paid,omitempty"`
	PaymentCurrency string                 `protobuf:"bytes,3,opt,name=payment_currency,json=paymentCurrency,proto3" json:"payment_currency,omitempty"`
	PaymentFormat   string                 `protobuf:"bytes,4,opt,name=payment_format,json=paymentFormat,proto3" json:"payment_format,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToConvertTransaction) Reset() {
	*x = ToConvertTransaction{}
	mi := &file_internal_common_inner_protobuf_conversion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToConvertTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToConvertTransaction) ProtoMessage() {}

func (x *ToConvertTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_conversion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToConvertTransaction.ProtoReflect.Descriptor instead.
func (*ToConvertTransaction) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_conversion_proto_rawDescGZIP(), []int{0}
}

func (x *ToConvertTransaction) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ToConvertTransaction) GetAmountPaid() string {
	if x != nil {
		return x.AmountPaid
	}
	return ""
}

func (x *ToConvertTransaction) GetPaymentCurrency() string {
	if x != nil {
		return x.PaymentCurrency
	}
	return ""
}

func (x *ToConvertTransaction) GetPaymentFormat() string {
	if x != nil {
		return x.PaymentFormat
	}
	return ""
}

type ToConvertPeriodFiltered struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AmountPaid      string                 `protobuf:"bytes,1,opt,name=amount_paid,json=amountPaid,proto3" json:"amount_paid,omitempty"`
	PaymentCurrency string                 `protobuf:"bytes,2,opt,name=payment_currency,json=paymentCurrency,proto3" json:"payment_currency,omitempty"`
	PaymentFormat   string                 `protobuf:"bytes,3,opt,name=payment_format,json=paymentFormat,proto3" json:"payment_format,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToConvertPeriodFiltered) Reset() {
	*x = ToConvertPeriodFiltered{}
	mi := &file_internal_common_inner_protobuf_conversion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToConvertPeriodFiltered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToConvertPeriodFiltered) ProtoMessage() {}

func (x *ToConvertPeriodFiltered) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_conversion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToConvertPeriodFiltered.ProtoReflect.Descriptor instead.
func (*ToConvertPeriodFiltered) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_conversion_proto_rawDescGZIP(), []int{1}
}

func (x *ToConvertPeriodFiltered) GetAmountPaid() string {
	if x != nil {
		return x.AmountPaid
	}
	return ""
}

func (x *ToConvertPeriodFiltered) GetPaymentCurrency() string {
	if x != nil {
		return x.PaymentCurrency
	}
	return ""
}

func (x *ToConvertPeriodFiltered) GetPaymentFormat() string {
	if x != nil {
		return x.PaymentFormat
	}
	return ""
}

type ToConvertTypeFilteredPayment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AmountPaid      string                 `protobuf:"bytes,1,opt,name=amount_paid,json=amountPaid,proto3" json:"amount_paid,omitempty"`
	PaymentCurrency string                 `protobuf:"bytes,2,opt,name=payment_currency,json=paymentCurrency,proto3" json:"payment_currency,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToConvertTypeFilteredPayment) Reset() {
	*x = ToConvertTypeFilteredPayment{}
	mi := &file_internal_common_inner_protobuf_conversion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToConvertTypeFilteredPayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToConvertTypeFilteredPayment) ProtoMessage() {}

func (x *ToConvertTypeFilteredPayment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_conversion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToConvertTypeFilteredPayment.ProtoReflect.Descriptor instead.
func (*ToConvertTypeFilteredPayment) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_conversion_proto_rawDescGZIP(), []int{2}
}

func (x *ToConvertTypeFilteredPayment) GetAmountPaid() string {
	if x != nil {
		return x.AmountPaid
	}
	return ""
}

func (x *ToConvertTypeFilteredPayment) GetPaymentCurrency() string {
	if x != nil {
		return x.PaymentCurrency
	}
	return ""
}

type ConvertedAmount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        string                 `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertedAmount) Reset() {
	*x = ConvertedAmount{}
	mi := &file_internal_common_inner_protobuf_conversion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertedAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertedAmount) ProtoMessage() {}

func (x *ConvertedAmount) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_conversion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertedAmount.ProtoReflect.Descriptor instead.
func (*ConvertedAmount) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_conversion_proto_rawDescGZIP(), []int{3}
}

func (x *ConvertedAmount) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type ConvertedMicroPaymentResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertedMicroPaymentResult) Reset() {
	*x = ConvertedMicroPaymentResult{}
	mi := &file_internal_common_inner_protobuf_conversion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertedMicroPaymentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertedMicroPaymentResult) ProtoMessage() {}

func (x *ConvertedMicroPaymentResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_conversion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertedMicroPaymentResult.ProtoReflect.Descriptor instead.
func (*ConvertedMicroPaymentResult) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_conversion_proto_rawDescGZIP(), []int{4}
}

func (x *ConvertedMicroPaymentResult) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_internal_common_inner_protobuf_conversion_proto protoreflect.FileDescriptor

const file_internal_common_inner_protobuf_conversion_proto_rawDesc = "" +
	"\n" +
	"/internal/common/inner/protobuf/conversion.proto\x12\bprotobuf\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc3\x01\n" +
	"\x14ToConvertTransaction\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\vamount_paid\x18\x02 \x01(\tR\n" +
	"amountPaid\x12)\n" +
	"\x10payment_currency\x18\x03 \x01(\tR\x0fpaymentCurrency\x12%\n" +
	"\x0epayment_format\x18\x04 \x01(\tR\rpaymentFormat\"\x8c\x01\n" +
	"\x17ToConvertPeriodFiltered\x12\x1f\n" +
	"\vamount_paid\x18\x01 \x01(\tR\n" +
	"amountPaid\x12)\n" +
	"\x10payment_currency\x18\x02 \x01(\tR\x0fpaymentCurrency\x12%\n" +
	"\x0epayment_format\x18\x03 \x01(\tR\rpaymentFormat\"j\n" +
	"\x1cToConvertTypeFilteredPayment\x12\x1f\n" +
	"\vamount_paid\x18\x01 \x01(\tR\n" +
	"amountPaid\x12)\n" +
	"\x10payment_currency\x18\x02 \x01(\tR\x0fpaymentCurrency\")\n" +
	"\x0fConvertedAmount\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\"3\n" +
	"\x1bConvertedMicroPaymentResult\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05countB1Z/tp-lavado-dinero/internal/common/inner/protobufb\x06proto3"

var (
	file_internal_common_inner_protobuf_conversion_proto_rawDescOnce sync.Once
	file_internal_common_inner_protobuf_conversion_proto_rawDescData []byte
)

func file_internal_common_inner_protobuf_conversion_proto_rawDescGZIP() []byte {
	file_internal_common_inner_protobuf_conversion_proto_rawDescOnce.Do(func() {
		file_internal_common_inner_protobuf_conversion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_conversion_proto_rawDesc), len(file_internal_common_inner_protobuf_conversion_proto_rawDesc)))
	})
	return file_internal_common_inner_protobuf_conversion_proto_rawDescData
}

var file_internal_common_inner_protobuf_conversion_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_common_inner_protobuf_conversion_proto_goTypes = []any{
	(*ToConvertTransaction)(nil),         // 0: protobuf.ToConvertTransaction
	(*ToConvertPeriodFiltered)(nil),      // 1: protobuf.ToConvertPeriodFiltered
	(*ToConvertTypeFilteredPayment)(nil), // 2: protobuf.ToConvertTypeFilteredPayment
	(*ConvertedAmount)(nil),              // 3: protobuf.ConvertedAmount
	(*ConvertedMicroPaymentResult)(nil),  // 4: protobuf.ConvertedMicroPaymentResult
	(*timestamppb.Timestamp)(nil),        // 5: google.protobuf.Timestamp
}
var file_internal_common_inner_protobuf_conversion_proto_depIdxs = []int32{
	5, // 0: protobuf.ToConvertTransaction.timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_common_inner_protobuf_conversion_proto_init() }
func file_internal_common_inner_protobuf_conversion_proto_init() {
	if File_internal_common_inner_protobuf_conversion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_conversion_proto_rawDesc), len(file_internal_common_inner_protobuf_conversion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_common_inner_protobuf_conversion_proto_goTypes,
		DependencyIndexes: file_internal_common_inner_protobuf_conversion_proto_depIdxs,
		MessageInfos:      file_internal_common_inner_protobuf_conversion_proto_msgTypes,
	}.Build()
	File_internal_common_inner_protobuf_conversion_proto = out.File
	file_internal_common_inner_protobuf_conversion_proto_goTypes = nil
	file_internal_common_inner_protobuf_conversion_proto_depIdxs = nil
}
