// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: tp-lavado-dinero/internal/common/inner/protobuf/groupedaccountsbatch.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bank          uint32                 `protobuf:"varint,1,opt,name=bank,proto3" json:"bank,omitempty"`
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetBank() uint32 {
	if x != nil {
		return x.Bank
	}
	return 0
}

func (x *Account) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type GroupedAccounts struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BaseAccount     *Account               `protobuf:"bytes,1,opt,name=base_account,json=baseAccount,proto3" json:"base_account,omitempty"`
	RelatedAccounts []*Account             `protobuf:"bytes,2,rep,name=related_accounts,json=relatedAccounts,proto3" json:"related_accounts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GroupedAccounts) Reset() {
	*x = GroupedAccounts{}
	mi := &file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupedAccounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupedAccounts) ProtoMessage() {}

func (x *GroupedAccounts) ProtoReflect() protoreflect.Message {
	mi := &file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupedAccounts.ProtoReflect.Descriptor instead.
func (*GroupedAccounts) Descriptor() ([]byte, []int) {
	return file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_rawDescGZIP(), []int{1}
}

func (x *GroupedAccounts) GetBaseAccount() *Account {
	if x != nil {
		return x.BaseAccount
	}
	return nil
}

func (x *GroupedAccounts) GetRelatedAccounts() []*Account {
	if x != nil {
		return x.RelatedAccounts
	}
	return nil
}

type GroupedAccountsBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*GroupedAccounts     `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupedAccountsBatch) Reset() {
	*x = GroupedAccountsBatch{}
	mi := &file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupedAccountsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupedAccountsBatch) ProtoMessage() {}

func (x *GroupedAccountsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupedAccountsBatch.ProtoReflect.Descriptor instead.
func (*GroupedAccountsBatch) Descriptor() ([]byte, []int) {
	return file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_rawDescGZIP(), []int{2}
}

func (x *GroupedAccountsBatch) GetGroups() []*GroupedAccounts {
	if x != nil {
		return x.Groups
	}
	return nil
}

var File_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto protoreflect.FileDescriptor

const file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_rawDesc = "" +
	"\n" +
	"Jtp-lavado-dinero/internal/common/inner/protobuf/groupedaccountsbatch.proto\x12\bprotobuf\"7\n" +
	"\aAccount\x12\x12\n" +
	"\x04bank\x18\x01 \x01(\rR\x04bank\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\"\x85\x01\n" +
	"\x0fGroupedAccounts\x124\n" +
	"\fbase_account\x18\x01 \x01(\v2\x11.protobuf.AccountR\vbaseAccount\x12<\n" +
	"\x10related_accounts\x18\x02 \x03(\v2\x11.protobuf.AccountR\x0frelatedAccounts\"I\n" +
	"\x14GroupedAccountsBatch\x121\n" +
	"\x06groups\x18\x01 \x03(\v2\x19.protobuf.GroupedAccountsR\x06groupsB1Z/tp-lavado-dinero/internal/common/inner/protobufb\x06proto3"

var (
	file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_rawDescOnce sync.Once
	file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_rawDescData []byte
)

func file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_rawDescGZIP() []byte {
	file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_rawDescOnce.Do(func() {
		file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_rawDesc), len(file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_rawDesc)))
	})
	return file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_rawDescData
}

var file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_goTypes = []any{
	(*Account)(nil),              // 0: protobuf.Account
	(*GroupedAccounts)(nil),      // 1: protobuf.GroupedAccounts
	(*GroupedAccountsBatch)(nil), // 2: protobuf.GroupedAccountsBatch
}
var file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_depIdxs = []int32{
	0, // 0: protobuf.GroupedAccounts.base_account:type_name -> protobuf.Account
	0, // 1: protobuf.GroupedAccounts.related_accounts:type_name -> protobuf.Account
	1, // 2: protobuf.GroupedAccountsBatch.groups:type_name -> protobuf.GroupedAccounts
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_init() }
func file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_init() {
	if File_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_rawDesc), len(file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_goTypes,
		DependencyIndexes: file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_depIdxs,
		MessageInfos:      file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_msgTypes,
	}.Build()
	File_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto = out.File
	file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_goTypes = nil
	file_tp_lavado_dinero_internal_common_inner_protobuf_groupedaccountsbatch_proto_depIdxs = nil
}
