// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/common/inner/protobuf/intermediarypair.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntermediaryPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intermediary  *Account               `protobuf:"bytes,1,opt,name=intermediary,proto3" json:"intermediary,omitempty"`
	Account       *Account               `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntermediaryPair) Reset() {
	*x = IntermediaryPair{}
	mi := &file_internal_common_inner_protobuf_intermediarypair_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntermediaryPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntermediaryPair) ProtoMessage() {}

func (x *IntermediaryPair) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_intermediarypair_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntermediaryPair.ProtoReflect.Descriptor instead.
func (*IntermediaryPair) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_intermediarypair_proto_rawDescGZIP(), []int{0}
}

func (x *IntermediaryPair) GetIntermediary() *Account {
	if x != nil {
		return x.Intermediary
	}
	return nil
}

func (x *IntermediaryPair) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type IntermediaryPairBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*IntermediaryPair    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntermediaryPairBatch) Reset() {
	*x = IntermediaryPairBatch{}
	mi := &file_internal_common_inner_protobuf_intermediarypair_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntermediaryPairBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntermediaryPairBatch) ProtoMessage() {}

func (x *IntermediaryPairBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_intermediarypair_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntermediaryPairBatch.ProtoReflect.Descriptor instead.
func (*IntermediaryPairBatch) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_intermediarypair_proto_rawDescGZIP(), []int{1}
}

func (x *IntermediaryPairBatch) GetItems() []*IntermediaryPair {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_internal_common_inner_protobuf_intermediarypair_proto protoreflect.FileDescriptor

const file_internal_common_inner_protobuf_intermediarypair_proto_rawDesc = "" +
	"\n" +
	"5internal/common/inner/protobuf/intermediarypair.proto\x12\bprotobuf\x1a,internal/common/inner/protobuf/account.proto\"v\n" +
	"\x10IntermediaryPair\x125\n" +
	"\fintermediary\x18\x01 \x01(\v2\x11.protobuf.AccountR\fintermediary\x12+\n" +
	"\aaccount\x18\x02 \x01(\v2\x11.protobuf.AccountR\aaccount\"I\n" +
	"\x15IntermediaryPairBatch\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.protobuf.IntermediaryPairR\x05itemsB1Z/tp-lavado-dinero/internal/common/inner/protobufb\x06proto3"

var (
	file_internal_common_inner_protobuf_intermediarypair_proto_rawDescOnce sync.Once
	file_internal_common_inner_protobuf_intermediarypair_proto_rawDescData []byte
)

func file_internal_common_inner_protobuf_intermediarypair_proto_rawDescGZIP() []byte {
	file_internal_common_inner_protobuf_intermediarypair_proto_rawDescOnce.Do(func() {
		file_internal_common_inner_protobuf_intermediarypair_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_intermediarypair_proto_rawDesc), len(file_internal_common_inner_protobuf_intermediarypair_proto_rawDesc)))
	})
	return file_internal_common_inner_protobuf_intermediarypair_proto_rawDescData
}

var file_internal_common_inner_protobuf_intermediarypair_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_common_inner_protobuf_intermediarypair_proto_goTypes = []any{
	(*IntermediaryPair)(nil),      // 0: protobuf.IntermediaryPair
	(*IntermediaryPairBatch)(nil), // 1: protobuf.IntermediaryPairBatch
	(*Account)(nil),               // 2: protobuf.Account
}
var file_internal_common_inner_protobuf_intermediarypair_proto_depIdxs = []int32{
	2, // 0: protobuf.IntermediaryPair.intermediary:type_name -> protobuf.Account
	2, // 1: protobuf.IntermediaryPair.account:type_name -> protobuf.Account
	0, // 2: protobuf.IntermediaryPairBatch.items:type_name -> protobuf.IntermediaryPair
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_common_inner_protobuf_intermediarypair_proto_init() }
func file_internal_common_inner_protobuf_intermediarypair_proto_init() {
	if File_internal_common_inner_protobuf_intermediarypair_proto != nil {
		return
	}
	file_internal_common_inner_protobuf_account_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_intermediarypair_proto_rawDesc), len(file_internal_common_inner_protobuf_intermediarypair_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_common_inner_protobuf_intermediarypair_proto_goTypes,
		DependencyIndexes: file_internal_common_inner_protobuf_intermediarypair_proto_depIdxs,
		MessageInfos:      file_internal_common_inner_protobuf_intermediarypair_proto_msgTypes,
	}.Build()
	File_internal_common_inner_protobuf_intermediarypair_proto = out.File
	file_internal_common_inner_protobuf_intermediarypair_proto_goTypes = nil
	file_internal_common_inner_protobuf_intermediarypair_proto_depIdxs = nil
}
