// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: intermediarypair.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntermediaryPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intermediary  *Account               `protobuf:"bytes,1,opt,name=intermediary,proto3" json:"intermediary,omitempty"`
	Account       *Account               `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntermediaryPair) Reset() {
	*x = IntermediaryPair{}
	mi := &file_intermediarypair_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntermediaryPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntermediaryPair) ProtoMessage() {}

func (x *IntermediaryPair) ProtoReflect() protoreflect.Message {
	mi := &file_intermediarypair_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntermediaryPair.ProtoReflect.Descriptor instead.
func (*IntermediaryPair) Descriptor() ([]byte, []int) {
	return file_intermediarypair_proto_rawDescGZIP(), []int{0}
}

func (x *IntermediaryPair) GetIntermediary() *Account {
	if x != nil {
		return x.Intermediary
	}
	return nil
}

func (x *IntermediaryPair) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

var File_intermediarypair_proto protoreflect.FileDescriptor

const file_intermediarypair_proto_rawDesc = "" +
	"\n" +
	"\x16intermediarypair.proto\x12\bprotobuf\x1a\raccount.proto\"v\n" +
	"\x10IntermediaryPair\x125\n" +
	"\fintermediary\x18\x01 \x01(\v2\x11.protobuf.AccountR\fintermediary\x12+\n" +
	"\aaccount\x18\x02 \x01(\v2\x11.protobuf.AccountR\aaccountB1Z/tp-lavado-dinero/internal/common/inner/protobufb\x06proto3"

var (
	file_intermediarypair_proto_rawDescOnce sync.Once
	file_intermediarypair_proto_rawDescData []byte
)

func file_intermediarypair_proto_rawDescGZIP() []byte {
	file_intermediarypair_proto_rawDescOnce.Do(func() {
		file_intermediarypair_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_intermediarypair_proto_rawDesc), len(file_intermediarypair_proto_rawDesc)))
	})
	return file_intermediarypair_proto_rawDescData
}

var file_intermediarypair_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_intermediarypair_proto_goTypes = []any{
	(*IntermediaryPair)(nil), // 0: protobuf.IntermediaryPair
	(*Account)(nil),          // 1: protobuf.Account
}
var file_intermediarypair_proto_depIdxs = []int32{
	1, // 0: protobuf.IntermediaryPair.intermediary:type_name -> protobuf.Account
	1, // 1: protobuf.IntermediaryPair.account:type_name -> protobuf.Account
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_intermediarypair_proto_init() }
func file_intermediarypair_proto_init() {
	if File_intermediarypair_proto != nil {
		return
	}
	file_account_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_intermediarypair_proto_rawDesc), len(file_intermediarypair_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_intermediarypair_proto_goTypes,
		DependencyIndexes: file_intermediarypair_proto_depIdxs,
		MessageInfos:      file_intermediarypair_proto_msgTypes,
	}.Build()
	File_intermediarypair_proto = out.File
	file_intermediarypair_proto_goTypes = nil
	file_intermediarypair_proto_depIdxs = nil
}
