// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: maxbank.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MaxBank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromBank      string                 `protobuf:"bytes,1,opt,name=from_bank,json=fromBank,proto3" json:"from_bank,omitempty"`
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaxBank) Reset() {
	*x = MaxBank{}
	mi := &file_maxbank_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaxBank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxBank) ProtoMessage() {}

func (x *MaxBank) ProtoReflect() protoreflect.Message {
	mi := &file_maxbank_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxBank.ProtoReflect.Descriptor instead.
func (*MaxBank) Descriptor() ([]byte, []int) {
	return file_maxbank_proto_rawDescGZIP(), []int{0}
}

func (x *MaxBank) GetFromBank() string {
	if x != nil {
		return x.FromBank
	}
	return ""
}

func (x *MaxBank) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *MaxBank) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

var File_maxbank_proto protoreflect.FileDescriptor

const file_maxbank_proto_rawDesc = "" +
	"\n" +
	"\rmaxbank.proto\x12\bprotobuf\"X\n" +
	"\aMaxBank\x12\x1b\n" +
	"\tfrom_bank\x18\x01 \x01(\tR\bfromBank\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amountB1Z/tp-lavado-dinero/internal/common/inner/protobufb\x06proto3"

var (
	file_maxbank_proto_rawDescOnce sync.Once
	file_maxbank_proto_rawDescData []byte
)

func file_maxbank_proto_rawDescGZIP() []byte {
	file_maxbank_proto_rawDescOnce.Do(func() {
		file_maxbank_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_maxbank_proto_rawDesc), len(file_maxbank_proto_rawDesc)))
	})
	return file_maxbank_proto_rawDescData
}

var file_maxbank_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_maxbank_proto_goTypes = []any{
	(*MaxBank)(nil), // 0: protobuf.MaxBank
}
var file_maxbank_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_maxbank_proto_init() }
func file_maxbank_proto_init() {
	if File_maxbank_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_maxbank_proto_rawDesc), len(file_maxbank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_maxbank_proto_goTypes,
		DependencyIndexes: file_maxbank_proto_depIdxs,
		MessageInfos:      file_maxbank_proto_msgTypes,
	}.Build()
	File_maxbank_proto = out.File
	file_maxbank_proto_goTypes = nil
	file_maxbank_proto_depIdxs = nil
}
