// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: tp-lavado-dinero/internal/common/inner/protobuf/microtransaction.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Microtransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	FromBank      int32                  `protobuf:"varint,2,opt,name=from_bank,json=fromBank,proto3" json:"from_bank,omitempty"`
	ToBank        int32                  `protobuf:"varint,3,opt,name=to_bank,json=toBank,proto3" json:"to_bank,omitempty"`
	Account       string                 `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	ToAccount     string                 `protobuf:"bytes,5,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	AmountPaid    string                 `protobuf:"bytes,6,opt,name=amount_paid,json=amountPaid,proto3" json:"amount_paid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Microtransaction) Reset() {
	*x = Microtransaction{}
	mi := &file_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Microtransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Microtransaction) ProtoMessage() {}

func (x *Microtransaction) ProtoReflect() protoreflect.Message {
	mi := &file_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Microtransaction.ProtoReflect.Descriptor instead.
func (*Microtransaction) Descriptor() ([]byte, []int) {
	return file_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto_rawDescGZIP(), []int{0}
}

func (x *Microtransaction) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *Microtransaction) GetFromBank() int32 {
	if x != nil {
		return x.FromBank
	}
	return 0
}

func (x *Microtransaction) GetToBank() int32 {
	if x != nil {
		return x.ToBank
	}
	return 0
}

func (x *Microtransaction) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Microtransaction) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *Microtransaction) GetAmountPaid() string {
	if x != nil {
		return x.AmountPaid
	}
	return ""
}

var File_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto protoreflect.FileDescriptor

const file_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto_rawDesc = "" +
	"\n" +
	"Ftp-lavado-dinero/internal/common/inner/protobuf/microtransaction.proto\x12\bprotobuf\"\xbe\x01\n" +
	"\x10Microtransaction\x12\x1a\n" +
	"\bclientID\x18\x01 \x01(\tR\bclientID\x12\x1b\n" +
	"\tfrom_bank\x18\x02 \x01(\x05R\bfromBank\x12\x17\n" +
	"\ato_bank\x18\x03 \x01(\x05R\x06toBank\x12\x18\n" +
	"\aaccount\x18\x04 \x01(\tR\aaccount\x12\x1d\n" +
	"\n" +
	"to_account\x18\x05 \x01(\tR\ttoAccount\x12\x1f\n" +
	"\vamount_paid\x18\x06 \x01(\tR\n" +
	"amountPaidB1Z/tp-lavado-dinero/internal/common/inner/protobufb\x06proto3"

var (
	file_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto_rawDescOnce sync.Once
	file_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto_rawDescData []byte
)

func file_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto_rawDescGZIP() []byte {
	file_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto_rawDescOnce.Do(func() {
		file_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto_rawDesc), len(file_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto_rawDesc)))
	})
	return file_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto_rawDescData
}

var file_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto_goTypes = []any{
	(*Microtransaction)(nil), // 0: protobuf.Microtransaction
}
var file_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto_init() }
func file_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto_init() {
	if File_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto_rawDesc), len(file_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto_goTypes,
		DependencyIndexes: file_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto_depIdxs,
		MessageInfos:      file_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto_msgTypes,
	}.Build()
	File_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto = out.File
	file_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto_goTypes = nil
	file_tp_lavado_dinero_internal_common_inner_protobuf_microtransaction_proto_depIdxs = nil
}
