// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: tp-lavado-dinero/internal/common/inner/protobuf/moneylaundry.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_EOF_                             MessageType = 0
	MessageType_TRANSACTION                      MessageType = 1
	MessageType_MICROTRANSACTION                 MessageType = 2
	MessageType_MAXBANK                          MessageType = 3
	MessageType_PERIODFILTER                     MessageType = 4
	MessageType_SCATTERGATHER                    MessageType = 5
	MessageType_GROUPED_ACCOUNTS_BATCH           MessageType = 6
	MessageType_INTERMEDIARYPAIR                 MessageType = 7
	MessageType_AVGBYTYPETRANSACTION             MessageType = 8
	MessageType_TO_CONVERT_TRANSACTION           MessageType = 9
	MessageType_TO_CONVERT_PERIOD_FILTERED       MessageType = 10
	MessageType_TO_CONVERT_TYPE_FILTERED_PAYMENT MessageType = 11
	MessageType_CONVERTED_AMOUNT                 MessageType = 12
	MessageType_MICROTRANSACTION_RESULT          MessageType = 13
	MessageType_MAXBANK_RESULT                   MessageType = 14
	MessageType_CONVERTED_MICRO_PAYMENT_RESULT   MessageType = 15
	MessageType_AVGBYTYPE_RESULT                 MessageType = 16
	MessageType_AVGBYTYPE_FIRST_PERIOD           MessageType = 17
	MessageType_AVGBYTYPE_SECOND_PERIOD          MessageType = 18
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "EOF_",
		1:  "TRANSACTION",
		2:  "MICROTRANSACTION",
		3:  "MAXBANK",
		4:  "PERIODFILTER",
		5:  "SCATTERGATHER",
		6:  "GROUPED_ACCOUNTS_BATCH",
		7:  "INTERMEDIARYPAIR",
		8:  "AVGBYTYPETRANSACTION",
		9:  "TO_CONVERT_TRANSACTION",
		10: "TO_CONVERT_PERIOD_FILTERED",
		11: "TO_CONVERT_TYPE_FILTERED_PAYMENT",
		12: "CONVERTED_AMOUNT",
		13: "MICROTRANSACTION_RESULT",
		14: "MAXBANK_RESULT",
		15: "CONVERTED_MICRO_PAYMENT_RESULT",
		16: "AVGBYTYPE_RESULT",
		17: "AVGBYTYPE_FIRST_PERIOD",
		18: "AVGBYTYPE_SECOND_PERIOD",
	}
	MessageType_value = map[string]int32{
		"EOF_":                             0,
		"TRANSACTION":                      1,
		"MICROTRANSACTION":                 2,
		"MAXBANK":                          3,
		"PERIODFILTER":                     4,
		"SCATTERGATHER":                    5,
		"GROUPED_ACCOUNTS_BATCH":           6,
		"INTERMEDIARYPAIR":                 7,
		"AVGBYTYPETRANSACTION":             8,
		"TO_CONVERT_TRANSACTION":           9,
		"TO_CONVERT_PERIOD_FILTERED":       10,
		"TO_CONVERT_TYPE_FILTERED_PAYMENT": 11,
		"CONVERTED_AMOUNT":                 12,
		"MICROTRANSACTION_RESULT":          13,
		"MAXBANK_RESULT":                   14,
		"CONVERTED_MICRO_PAYMENT_RESULT":   15,
		"AVGBYTYPE_RESULT":                 16,
		"AVGBYTYPE_FIRST_PERIOD":           17,
		"AVGBYTYPE_SECOND_PERIOD":          18,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_rawDescGZIP(), []int{0}
}

type MoneyLaundry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	Type          MessageType            `protobuf:"varint,2,opt,name=type,proto3,enum=protobuf.MessageType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoneyLaundry) Reset() {
	*x = MoneyLaundry{}
	mi := &file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoneyLaundry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoneyLaundry) ProtoMessage() {}

func (x *MoneyLaundry) ProtoReflect() protoreflect.Message {
	mi := &file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoneyLaundry.ProtoReflect.Descriptor instead.
func (*MoneyLaundry) Descriptor() ([]byte, []int) {
	return file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_rawDescGZIP(), []int{0}
}

func (x *MoneyLaundry) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *MoneyLaundry) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_EOF_
}

func (x *MoneyLaundry) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto protoreflect.FileDescriptor

const file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_rawDesc = "" +
	"\n" +
	"Btp-lavado-dinero/internal/common/inner/protobuf/moneylaundry.proto\x12\bprotobuf\"o\n" +
	"\fMoneyLaundry\x12\x1a\n" +
	"\bclientID\x18\x01 \x01(\tR\bclientID\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.protobuf.MessageTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload*\xd8\x03\n" +
	"\vMessageType\x12\b\n" +
	"\x04EOF_\x10\x00\x12\x0f\n" +
	"\vTRANSACTION\x10\x01\x12\x14\n" +
	"\x10MICROTRANSACTION\x10\x02\x12\v\n" +
	"\aMAXBANK\x10\x03\x12\x10\n" +
	"\fPERIODFILTER\x10\x04\x12\x11\n" +
	"\rSCATTERGATHER\x10\x05\x12\x1a\n" +
	"\x16GROUPED_ACCOUNTS_BATCH\x10\x06\x12\x14\n" +
	"\x10INTERMEDIARYPAIR\x10\a\x12\x18\n" +
	"\x14AVGBYTYPETRANSACTION\x10\b\x12\x1a\n" +
	"\x16TO_CONVERT_TRANSACTION\x10\t\x12\x1e\n" +
	"\x1aTO_CONVERT_PERIOD_FILTERED\x10\n" +
	"\x12$\n" +
	" TO_CONVERT_TYPE_FILTERED_PAYMENT\x10\v\x12\x14\n" +
	"\x10CONVERTED_AMOUNT\x10\f\x12\x1b\n" +
	"\x17MICROTRANSACTION_RESULT\x10\r\x12\x12\n" +
	"\x0eMAXBANK_RESULT\x10\x0e\x12\"\n" +
	"\x1eCONVERTED_MICRO_PAYMENT_RESULT\x10\x0f\x12\x14\n" +
	"\x10AVGBYTYPE_RESULT\x10\x10\x12\x1a\n" +
	"\x16AVGBYTYPE_FIRST_PERIOD\x10\x11\x12\x1b\n" +
	"\x17AVGBYTYPE_SECOND_PERIOD\x10\x12B1Z/tp-lavado-dinero/internal/common/inner/protobufb\x06proto3"

var (
	file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_rawDescOnce sync.Once
	file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_rawDescData []byte
)

func file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_rawDescGZIP() []byte {
	file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_rawDescOnce.Do(func() {
		file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_rawDesc), len(file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_rawDesc)))
	})
	return file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_rawDescData
}

var file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_goTypes = []any{
	(MessageType)(0),     // 0: protobuf.MessageType
	(*MoneyLaundry)(nil), // 1: protobuf.MoneyLaundry
}
var file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_depIdxs = []int32{
	0, // 0: protobuf.MoneyLaundry.type:type_name -> protobuf.MessageType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_init() }
func file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_init() {
	if File_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_rawDesc), len(file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_goTypes,
		DependencyIndexes: file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_depIdxs,
		EnumInfos:         file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_enumTypes,
		MessageInfos:      file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_msgTypes,
	}.Build()
	File_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto = out.File
	file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_goTypes = nil
	file_tp_lavado_dinero_internal_common_inner_protobuf_moneylaundry_proto_depIdxs = nil
}
