// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/common/inner/protobuf/scattergather.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScatterGather struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromBank      int32                  `protobuf:"varint,1,opt,name=from_bank,json=fromBank,proto3" json:"from_bank,omitempty"`
	ToBank        int32                  `protobuf:"varint,2,opt,name=to_bank,json=toBank,proto3" json:"to_bank,omitempty"`
	Account       string                 `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	ToAccount     string                 `protobuf:"bytes,4,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScatterGather) Reset() {
	*x = ScatterGather{}
	mi := &file_internal_common_inner_protobuf_scattergather_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScatterGather) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScatterGather) ProtoMessage() {}

func (x *ScatterGather) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_scattergather_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScatterGather.ProtoReflect.Descriptor instead.
func (*ScatterGather) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_scattergather_proto_rawDescGZIP(), []int{0}
}

func (x *ScatterGather) GetFromBank() int32 {
	if x != nil {
		return x.FromBank
	}
	return 0
}

func (x *ScatterGather) GetToBank() int32 {
	if x != nil {
		return x.ToBank
	}
	return 0
}

func (x *ScatterGather) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ScatterGather) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

type ScatterGatherBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ScatterGather       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScatterGatherBatch) Reset() {
	*x = ScatterGatherBatch{}
	mi := &file_internal_common_inner_protobuf_scattergather_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScatterGatherBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScatterGatherBatch) ProtoMessage() {}

func (x *ScatterGatherBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_scattergather_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScatterGatherBatch.ProtoReflect.Descriptor instead.
func (*ScatterGatherBatch) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_scattergather_proto_rawDescGZIP(), []int{1}
}

func (x *ScatterGatherBatch) GetItems() []*ScatterGather {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_internal_common_inner_protobuf_scattergather_proto protoreflect.FileDescriptor

const file_internal_common_inner_protobuf_scattergather_proto_rawDesc = "" +
	"\n" +
	"2internal/common/inner/protobuf/scattergather.proto\x12\bprotobuf\"~\n" +
	"\rScatterGather\x12\x1b\n" +
	"\tfrom_bank\x18\x01 \x01(\x05R\bfromBank\x12\x17\n" +
	"\ato_bank\x18\x02 \x01(\x05R\x06toBank\x12\x18\n" +
	"\aaccount\x18\x03 \x01(\tR\aaccount\x12\x1d\n" +
	"\n" +
	"to_account\x18\x04 \x01(\tR\ttoAccount\"C\n" +
	"\x12ScatterGatherBatch\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.protobuf.ScatterGatherR\x05itemsB1Z/tp-lavado-dinero/internal/common/inner/protobufb\x06proto3"

var (
	file_internal_common_inner_protobuf_scattergather_proto_rawDescOnce sync.Once
	file_internal_common_inner_protobuf_scattergather_proto_rawDescData []byte
)

func file_internal_common_inner_protobuf_scattergather_proto_rawDescGZIP() []byte {
	file_internal_common_inner_protobuf_scattergather_proto_rawDescOnce.Do(func() {
		file_internal_common_inner_protobuf_scattergather_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_scattergather_proto_rawDesc), len(file_internal_common_inner_protobuf_scattergather_proto_rawDesc)))
	})
	return file_internal_common_inner_protobuf_scattergather_proto_rawDescData
}

var file_internal_common_inner_protobuf_scattergather_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_common_inner_protobuf_scattergather_proto_goTypes = []any{
	(*ScatterGather)(nil),      // 0: protobuf.ScatterGather
	(*ScatterGatherBatch)(nil), // 1: protobuf.ScatterGatherBatch
}
var file_internal_common_inner_protobuf_scattergather_proto_depIdxs = []int32{
	0, // 0: protobuf.ScatterGatherBatch.items:type_name -> protobuf.ScatterGather
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_common_inner_protobuf_scattergather_proto_init() }
func file_internal_common_inner_protobuf_scattergather_proto_init() {
	if File_internal_common_inner_protobuf_scattergather_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_scattergather_proto_rawDesc), len(file_internal_common_inner_protobuf_scattergather_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_common_inner_protobuf_scattergather_proto_goTypes,
		DependencyIndexes: file_internal_common_inner_protobuf_scattergather_proto_depIdxs,
		MessageInfos:      file_internal_common_inner_protobuf_scattergather_proto_msgTypes,
	}.Build()
	File_internal_common_inner_protobuf_scattergather_proto = out.File
	file_internal_common_inner_protobuf_scattergather_proto_goTypes = nil
	file_internal_common_inner_protobuf_scattergather_proto_depIdxs = nil
}
