// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: suspiciouspath.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SuspiciousPath struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Origin            *Account               `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination       *Account               `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	IntermediaryCount uint32                 `protobuf:"varint,3,opt,name=intermediary_count,json=intermediaryCount,proto3" json:"intermediary_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SuspiciousPath) Reset() {
	*x = SuspiciousPath{}
	mi := &file_suspiciouspath_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspiciousPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspiciousPath) ProtoMessage() {}

func (x *SuspiciousPath) ProtoReflect() protoreflect.Message {
	mi := &file_suspiciouspath_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspiciousPath.ProtoReflect.Descriptor instead.
func (*SuspiciousPath) Descriptor() ([]byte, []int) {
	return file_suspiciouspath_proto_rawDescGZIP(), []int{0}
}

func (x *SuspiciousPath) GetOrigin() *Account {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *SuspiciousPath) GetDestination() *Account {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *SuspiciousPath) GetIntermediaryCount() uint32 {
	if x != nil {
		return x.IntermediaryCount
	}
	return 0
}

type SuspiciousPathBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []*SuspiciousPath      `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspiciousPathBatch) Reset() {
	*x = SuspiciousPathBatch{}
	mi := &file_suspiciouspath_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspiciousPathBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspiciousPathBatch) ProtoMessage() {}

func (x *SuspiciousPathBatch) ProtoReflect() protoreflect.Message {
	mi := &file_suspiciouspath_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspiciousPathBatch.ProtoReflect.Descriptor instead.
func (*SuspiciousPathBatch) Descriptor() ([]byte, []int) {
	return file_suspiciouspath_proto_rawDescGZIP(), []int{1}
}

func (x *SuspiciousPathBatch) GetPaths() []*SuspiciousPath {
	if x != nil {
		return x.Paths
	}
	return nil
}

var File_suspiciouspath_proto protoreflect.FileDescriptor

const file_suspiciouspath_proto_rawDesc = "" +
	"\n" +
	"\x14suspiciouspath.proto\x12\bprotobuf\x1a\raccount.proto\"\x9f\x01\n" +
	"\x0eSuspiciousPath\x12)\n" +
	"\x06origin\x18\x01 \x01(\v2\x11.protobuf.AccountR\x06origin\x123\n" +
	"\vdestination\x18\x02 \x01(\v2\x11.protobuf.AccountR\vdestination\x12-\n" +
	"\x12intermediary_count\x18\x03 \x01(\rR\x11intermediaryCount\"E\n" +
	"\x13SuspiciousPathBatch\x12.\n" +
	"\x05paths\x18\x01 \x03(\v2\x18.protobuf.SuspiciousPathR\x05pathsB1Z/tp-lavado-dinero/internal/common/inner/protobufb\x06proto3"

var (
	file_suspiciouspath_proto_rawDescOnce sync.Once
	file_suspiciouspath_proto_rawDescData []byte
)

func file_suspiciouspath_proto_rawDescGZIP() []byte {
	file_suspiciouspath_proto_rawDescOnce.Do(func() {
		file_suspiciouspath_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_suspiciouspath_proto_rawDesc), len(file_suspiciouspath_proto_rawDesc)))
	})
	return file_suspiciouspath_proto_rawDescData
}

var file_suspiciouspath_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_suspiciouspath_proto_goTypes = []any{
	(*SuspiciousPath)(nil),      // 0: protobuf.SuspiciousPath
	(*SuspiciousPathBatch)(nil), // 1: protobuf.SuspiciousPathBatch
	(*Account)(nil),             // 2: protobuf.Account
}
var file_suspiciouspath_proto_depIdxs = []int32{
	2, // 0: protobuf.SuspiciousPath.origin:type_name -> protobuf.Account
	2, // 1: protobuf.SuspiciousPath.destination:type_name -> protobuf.Account
	0, // 2: protobuf.SuspiciousPathBatch.paths:type_name -> protobuf.SuspiciousPath
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_suspiciouspath_proto_init() }
func file_suspiciouspath_proto_init() {
	if File_suspiciouspath_proto != nil {
		return
	}
	file_account_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_suspiciouspath_proto_rawDesc), len(file_suspiciouspath_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_suspiciouspath_proto_goTypes,
		DependencyIndexes: file_suspiciouspath_proto_depIdxs,
		MessageInfos:      file_suspiciouspath_proto_msgTypes,
	}.Build()
	File_suspiciouspath_proto = out.File
	file_suspiciouspath_proto_goTypes = nil
	file_suspiciouspath_proto_depIdxs = nil
}
