// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: suspiciousaccount.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SuspiciousAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspiciousAccount) Reset() {
	*x = SuspiciousAccount{}
	mi := &file_suspiciousaccount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspiciousAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspiciousAccount) ProtoMessage() {}

func (x *SuspiciousAccount) ProtoReflect() protoreflect.Message {
	mi := &file_suspiciousaccount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspiciousAccount.ProtoReflect.Descriptor instead.
func (*SuspiciousAccount) Descriptor() ([]byte, []int) {
	return file_suspiciousaccount_proto_rawDescGZIP(), []int{0}
}

func (x *SuspiciousAccount) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type SuspiciousAccountBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*SuspiciousAccount   `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspiciousAccountBatch) Reset() {
	*x = SuspiciousAccountBatch{}
	mi := &file_suspiciousaccount_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspiciousAccountBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspiciousAccountBatch) ProtoMessage() {}

func (x *SuspiciousAccountBatch) ProtoReflect() protoreflect.Message {
	mi := &file_suspiciousaccount_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspiciousAccountBatch.ProtoReflect.Descriptor instead.
func (*SuspiciousAccountBatch) Descriptor() ([]byte, []int) {
	return file_suspiciousaccount_proto_rawDescGZIP(), []int{1}
}

func (x *SuspiciousAccountBatch) GetAccounts() []*SuspiciousAccount {
	if x != nil {
		return x.Accounts
	}
	return nil
}

var File_suspiciousaccount_proto protoreflect.FileDescriptor

const file_suspiciousaccount_proto_rawDesc = "" +
	"\n" +
	"\x17suspiciousaccount.proto\x12\bprotobuf\x1a\raccount.proto\"@\n" +
	"\x11SuspiciousAccount\x12+\n" +
	"\aaccount\x18\x01 \x01(\v2\x11.protobuf.AccountR\aaccount\"Q\n" +
	"\x16SuspiciousAccountBatch\x127\n" +
	"\baccounts\x18\x01 \x03(\v2\x1b.protobuf.SuspiciousAccountR\baccountsB1Z/tp-lavado-dinero/internal/common/inner/protobufb\x06proto3"

var (
	file_suspiciousaccount_proto_rawDescOnce sync.Once
	file_suspiciousaccount_proto_rawDescData []byte
)

func file_suspiciousaccount_proto_rawDescGZIP() []byte {
	file_suspiciousaccount_proto_rawDescOnce.Do(func() {
		file_suspiciousaccount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_suspiciousaccount_proto_rawDesc), len(file_suspiciousaccount_proto_rawDesc)))
	})
	return file_suspiciousaccount_proto_rawDescData
}

var file_suspiciousaccount_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_suspiciousaccount_proto_goTypes = []any{
	(*SuspiciousAccount)(nil),      // 0: protobuf.SuspiciousAccount
	(*SuspiciousAccountBatch)(nil), // 1: protobuf.SuspiciousAccountBatch
	(*Account)(nil),                // 2: protobuf.Account
}
var file_suspiciousaccount_proto_depIdxs = []int32{
	2, // 0: protobuf.SuspiciousAccount.account:type_name -> protobuf.Account
	0, // 1: protobuf.SuspiciousAccountBatch.accounts:type_name -> protobuf.SuspiciousAccount
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_suspiciousaccount_proto_init() }
func file_suspiciousaccount_proto_init() {
	if File_suspiciousaccount_proto != nil {
		return
	}
	file_account_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_suspiciousaccount_proto_rawDesc), len(file_suspiciousaccount_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_suspiciousaccount_proto_goTypes,
		DependencyIndexes: file_suspiciousaccount_proto_depIdxs,
		MessageInfos:      file_suspiciousaccount_proto_msgTypes,
	}.Build()
	File_suspiciousaccount_proto = out.File
	file_suspiciousaccount_proto_goTypes = nil
	file_suspiciousaccount_proto_depIdxs = nil
}
