// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/common/inner/protobuf/transaction.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	FromBank        int32                  `protobuf:"varint,2,opt,name=from_bank,json=fromBank,proto3" json:"from_bank,omitempty"`
	ToBank          int32                  `protobuf:"varint,3,opt,name=to_bank,json=toBank,proto3" json:"to_bank,omitempty"`
	Account         string                 `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	ToAccount       string                 `protobuf:"bytes,5,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	PaymentCurrency string                 `protobuf:"bytes,6,opt,name=payment_currency,json=paymentCurrency,proto3" json:"payment_currency,omitempty"`
	AmountPaid      string                 `protobuf:"bytes,7,opt,name=amount_paid,json=amountPaid,proto3" json:"amount_paid,omitempty"` //	chequear el tipo de este campo.
	PaymentFormat   string                 `protobuf:"bytes,8,opt,name=payment_format,json=paymentFormat,proto3" json:"payment_format,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_internal_common_inner_protobuf_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_common_inner_protobuf_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_internal_common_inner_protobuf_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Transaction) GetFromBank() int32 {
	if x != nil {
		return x.FromBank
	}
	return 0
}

func (x *Transaction) GetToBank() int32 {
	if x != nil {
		return x.ToBank
	}
	return 0
}

func (x *Transaction) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Transaction) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *Transaction) GetPaymentCurrency() string {
	if x != nil {
		return x.PaymentCurrency
	}
	return ""
}

func (x *Transaction) GetAmountPaid() string {
	if x != nil {
		return x.AmountPaid
	}
	return ""
}

func (x *Transaction) GetPaymentFormat() string {
	if x != nil {
		return x.PaymentFormat
	}
	return ""
}

var File_internal_common_inner_protobuf_transaction_proto protoreflect.FileDescriptor

const file_internal_common_inner_protobuf_transaction_proto_rawDesc = "" +
	"\n" +
	"0internal/common/inner/protobuf/transaction.proto\x12\bprotobuf\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa9\x02\n" +
	"\vTransaction\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\tfrom_bank\x18\x02 \x01(\x05R\bfromBank\x12\x17\n" +
	"\ato_bank\x18\x03 \x01(\x05R\x06toBank\x12\x18\n" +
	"\aaccount\x18\x04 \x01(\tR\aaccount\x12\x1d\n" +
	"\n" +
	"to_account\x18\x05 \x01(\tR\ttoAccount\x12)\n" +
	"\x10payment_currency\x18\x06 \x01(\tR\x0fpaymentCurrency\x12\x1f\n" +
	"\vamount_paid\x18\a \x01(\tR\n" +
	"amountPaid\x12%\n" +
	"\x0epayment_format\x18\b \x01(\tR\rpaymentFormatB1Z/tp-lavado-dinero/internal/common/inner/protobufb\x06proto3"

var (
	file_internal_common_inner_protobuf_transaction_proto_rawDescOnce sync.Once
	file_internal_common_inner_protobuf_transaction_proto_rawDescData []byte
)

func file_internal_common_inner_protobuf_transaction_proto_rawDescGZIP() []byte {
	file_internal_common_inner_protobuf_transaction_proto_rawDescOnce.Do(func() {
		file_internal_common_inner_protobuf_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_transaction_proto_rawDesc), len(file_internal_common_inner_protobuf_transaction_proto_rawDesc)))
	})
	return file_internal_common_inner_protobuf_transaction_proto_rawDescData
}

var file_internal_common_inner_protobuf_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_common_inner_protobuf_transaction_proto_goTypes = []any{
	(*Transaction)(nil),           // 0: protobuf.Transaction
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_internal_common_inner_protobuf_transaction_proto_depIdxs = []int32{
	1, // 0: protobuf.Transaction.timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_common_inner_protobuf_transaction_proto_init() }
func file_internal_common_inner_protobuf_transaction_proto_init() {
	if File_internal_common_inner_protobuf_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_common_inner_protobuf_transaction_proto_rawDesc), len(file_internal_common_inner_protobuf_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_common_inner_protobuf_transaction_proto_goTypes,
		DependencyIndexes: file_internal_common_inner_protobuf_transaction_proto_depIdxs,
		MessageInfos:      file_internal_common_inner_protobuf_transaction_proto_msgTypes,
	}.Build()
	File_internal_common_inner_protobuf_transaction_proto = out.File
	file_internal_common_inner_protobuf_transaction_proto_goTypes = nil
	file_internal_common_inner_protobuf_transaction_proto_depIdxs = nil
}
